#!/usr/bin/env python3
"""Add AI-generated example sentences to all supplement vocabulary entries."""
import json
from pathlib import Path

BASE = Path(__file__).parent
SUPP_PATH = BASE / "vocab-supplement.json"

# Example sentences for each supplement word, keyed by "(unit) word"
# Format: (english_sentence, chinese_translation)
SENTENCES = {
    # ===== st01 =====
    "I": ("I am a student.", "我是一名学生。"),
    "am": ("I am twelve years old.", "我十二岁。"),
    "are": ("You are my friend.", "你是我的朋友。"),
    "you": ("You are nice.", "你很好。"),
    "Mrs.": ("Good morning, Mrs. Wang.", "早上好，王老师。"),
    "Mr.": ("Hello, Mr. Li.", "你好，李老师。"),
    "Ms.": ("Ms. Chen is our teacher.", "陈老师是我们的老师。"),
    "Miss": ("Miss Liu is very kind.", "刘老师很和蔼。"),
    "how": ("How are you?", "你好吗？"),
    "stand": ("Please stand up.", "请起立。"),
    "up": ("Stand up, please.", "请起立。"),
    "sit": ("Sit down, please.", "请坐下。"),
    "down": ("Please sit down.", "请坐下。"),
    "please": ("Come in, please.", "请进。"),
    "thank": ("Thank you very much.", "非常感谢你。"),
    "see": ("I see a cat.", "我看见一只猫。"),
    "yes": ("Yes, I do.", "是的，我做。"),
    "no": ("No, it isn't.", "不，它不是。"),
    "sorry": ("I am sorry.", "对不起。"),
    "OK": ("OK, let's go.", "好的，我们走吧。"),
    # ===== st02 =====
    "what": ("What is this?", "这是什么？"),
    "this": ("This is a book.", "这是一本书。"),
    "in": ("It is in my bag.", "它在我的包里。"),
    "English": ("I like English.", "我喜欢英语。"),
    "a": ("I have a pen.", "我有一支钢笔。"),
    "an": ("It is an apple.", "它是一个苹果。"),
    "it": ("It is big.", "它很大。"),
    "that": ("That is a ruler.", "那是一把尺子。"),
    "spell": ("Can you spell it?", "你能拼写它吗？"),
    "map": ("This is a map.", "这是一张地图。"),
    "cup": ("The cup is on the desk.", "杯子在桌子上。"),
    "pen": ("I have a blue pen.", "我有一支蓝色钢笔。"),
    "orange": ("The orange is sweet.", "橙子很甜。"),
    "jacket": ("My jacket is red.", "我的夹克是红色的。"),
    "key": ("This is my key.", "这是我的钥匙。"),
    "ruler": ("This is my ruler.", "这是我的尺子。"),
    "quilt": ("The quilt is warm.", "被子很暖和。"),
    # ===== st03 =====
    "color": ("What color is it?", "它是什么颜色？"),
    "red": ("The apple is red.", "苹果是红色的。"),
    "yellow": ("The banana is yellow.", "香蕉是黄色的。"),
    "green": ("The grass is green.", "草是绿色的。"),
    "blue": ("The sky is blue.", "天空是蓝色的。"),
    "black": ("My bag is black.", "我的包是黑色的。"),
    "white": ("Snow is white.", "雪是白色的。"),
    "purple": ("I like purple flowers.", "我喜欢紫色的花。"),
    "brown": ("The dog is brown.", "狗是棕色的。"),
    "pink": ("Her dress is pink.", "她的裙子是粉色的。"),
    "now": ("Let's go now.", "我们现在走吧。"),
    "can": ("I can swim.", "我会游泳。"),
    "say": ("Please say it again.", "请再说一遍。"),
    "my": ("This is my book.", "这是我的书。"),
    "your": ("Is this your pencil?", "这是你的铅笔吗？"),
    # ===== u01 =====
    "I'm": ("I'm a student.", "我是一名学生。"),
    "his": ("His name is Tom.", "他的名字是汤姆。"),
    "her": ("Her bag is blue.", "她的包是蓝色的。"),
    "she": ("She is my sister.", "她是我的妹妹。"),
    "he": ("He is tall.", "他很高。"),
    "not": ("It is not my pen.", "这不是我的钢笔。"),
    "aren't": ("You aren't late.", "你没有迟到。"),
    "isn't": ("It isn't my book.", "那不是我的书。"),
    "China": ("China is a great country.", "中国是一个伟大的国家。"),
    "American": ("She is American.", "她是美国人。"),
    "too": ("I like it, too.", "我也喜欢它。"),
    "very": ("Thank you very much.", "非常感谢你。"),
    "and": ("I like apples and bananas.", "我喜欢苹果和香蕉。"),
    "but": ("I like cats but not dogs.", "我喜欢猫但不喜欢狗。"),
    "or": ("Is it red or blue?", "它是红色的还是蓝色的？"),
    "hi": ("Hi, how are you?", "嗨，你好吗？"),
    "hello": ("Hello, everyone!", "大家好！"),
    "goodbye": ("Goodbye, see you!", "再见，回头见！"),
    "bye": ("Bye, Mom!", "再见，妈妈！"),
    # ===== u02 =====
    "sister": ("My sister is ten.", "我的妹妹十岁。"),
    "brother": ("My brother is tall.", "我的哥哥很高。"),
    "mother": ("My mother is a teacher.", "我妈妈是一名老师。"),
    "father": ("My father is kind.", "我爸爸很和蔼。"),
    "parent": ("My parents love me.", "我的父母爱我。"),
    "grandmother": ("My grandmother is old.", "我的奶奶年纪大了。"),
    "grandfather": ("My grandfather has white hair.", "我的爷爷有白头发。"),
    "family": ("I have a happy family.", "我有一个幸福的家庭。"),
    "those": ("Those are my books.", "那些是我的书。"),
    "these": ("These are pencils.", "这些是铅笔。"),
    "who": ("Who is she?", "她是谁？"),
    "they": ("They are my friends.", "他们是我的朋友。"),
    "well": ("Well, let's go.", "嗯，我们走吧。"),
    "have": ("I have a dog.", "我有一只狗。"),
    "day": ("Have a nice day!", "祝你有美好的一天！"),
    "dear": ("Dear mom, I miss you.", "亲爱的妈妈，我想你。"),
    "photo": ("This is a family photo.", "这是一张全家福。"),
    "picture": ("I draw a picture.", "我画了一幅画。"),
    "girl": ("The girl is my classmate.", "那个女孩是我的同学。"),
    "boy": ("The boy is my friend.", "那个男孩是我的朋友。"),
    "aunt": ("My aunt is a doctor.", "我阿姨是医生。"),
    "uncle": ("My uncle is tall and strong.", "我叔叔又高又壮。"),
    "son": ("Her son is five.", "她的儿子五岁。"),
    "daughter": ("His daughter is cute.", "他的女儿很可爱。"),
    "cousin": ("My cousin is my good friend.", "我的表弟是我的好朋友。"),
    # ===== u03 =====
    "pencil": ("I have a new pencil.", "我有一支新铅笔。"),
    "book": ("I like reading books.", "我喜欢读书。"),
    "eraser": ("I use an eraser to clean my mistake.", "我用橡皮擦掉错误。"),
    "schoolbag": ("My schoolbag is heavy with books.", "我的书包装满了书很重。"),
    "dictionary": ("I look up new words in the dictionary.", "我在字典里查生词。"),
    "ring": ("The ring is made of silver.", "这枚戒指是银制的。"),
    "teacher": ("My teacher is nice.", "我的老师很好。"),
    "student": ("I am a student.", "我是一名学生。"),
    "classroom": ("Our classroom is big.", "我们的教室很大。"),
    "school": ("I go to school every day.", "我每天都去上学。"),
    "library": ("I read in the library.", "我在图书馆看书。"),
    "bag": ("My bag is heavy.", "我的包很重。"),
    "baseball": ("I like playing baseball.", "我喜欢打棒球。"),
    "some": ("I have some apples.", "我有一些苹果。"),
    "find": ("I can't find my pen.", "我找不到我的钢笔了。"),
    "lost": ("I lost my keys.", "我丢了钥匙。"),
    "call": ("Please call me.", "请给我打电话。"),
    "must": ("I must go now.", "我现在必须走了。"),
    "help": ("Can you help me?", "你能帮我吗？"),
    "excuse": ("Excuse me, where is the library?", "打扰一下，图书馆在哪里？"),
    "me": ("Please give me the book.", "请把书给我。"),
    # ===== u04 =====
    "where": ("Where is my bag?", "我的包在哪里？"),
    "come": ("Come here, please.", "请过来。"),
    "go": ("Let's go home.", "我们回家吧。"),
    "desk": ("My desk is tidy.", "我的书桌很整洁。"),
    "chair": ("The chair is under the desk.", "椅子在书桌下面。"),
    "table": ("The book is on the table.", "书在桌子上。"),
    "bed": ("I sleep on my bed.", "我在床上睡觉。"),
    "bookcase": ("The bookcase is full of books.", "书架上全是书。"),
    "sofa": ("My cat sits on the sofa.", "我的猫坐在沙发上。"),
    "drawer": ("I keep my pens in the drawer.", "我把钢笔放在抽屉里。"),
    "plant": ("There is a plant in the room.", "房间里有一盆植物。"),
    "tidy": ("Please keep your room tidy.", "请保持房间整洁。"),
    "everywhere": ("My books are everywhere.", "我的书到处都是。"),
    "always": ("I always get up early.", "我总是早起。"),
    "room": ("This is my room.", "这是我的房间。"),
    "hat": ("I wear a hat in summer.", "夏天我戴帽子。"),
    "head": ("My head hurts.", "我头疼。"),
    "know": ("I know the answer.", "我知道答案。"),
    "think": ("I think it is a good idea.", "我认为这是个好主意。"),
    "radio": ("My grandpa listens to the radio.", "我爷爷听收音机。"),
    "clock": ("The clock on the wall is new.", "墙上的钟是新的。"),
    "tape": ("I have a tape player.", "我有一个磁带播放器。"),
    "player": ("My brother has a new player.", "我哥哥有一个新播放器。"),
    "model": ("I make a model plane.", "我做了一个飞机模型。"),
    "plane": ("The plane is flying in the sky.", "飞机正在天空中飞行。"),
    # ===== u05 =====
    "soccer": ("I like playing soccer.", "我喜欢踢足球。"),
    "basketball": ("Basketball is fun.", "篮球很有趣。"),
    "tennis": ("I play tennis with my friend.", "我和朋友打网球。"),
    "volleyball": ("She is good at volleyball.", "她擅长排球。"),
    "ping-pong": ("We play ping-pong after school.", "放学后我们打乒乓球。"),
    "ball": ("The ball is under the chair.", "球在椅子下面。"),
    "bat": ("I need a bat to play baseball.", "打棒球需要球棒。"),
    "interesting": ("This book is interesting.", "这本书很有趣。"),
    "boring": ("The movie is boring.", "这部电影很无聊。"),
    "difficult": ("Math is difficult for me.", "数学对我来说很难。"),
    "easy": ("This test is easy.", "这次考试很容易。"),
    "fun": ("We have fun at the party.", "我们在聚会上玩得很开心。"),
    "relaxing": ("Listening to music is relaxing.", "听音乐很放松。"),
    "great": ("That sounds great!", "听起来很棒！"),
    "play": ("I play basketball after school.", "我放学后打篮球。"),
    "watch": ("I watch TV in the evening.", "我晚上看电视。"),
    "let": ("Let me help you.", "让我帮你。"),
    "us": ("Let us go to the park.", "我们去公园吧。"),
    "late": ("Don't be late for class.", "上课不要迟到。"),
    "classmate": ("My classmate is very kind.", "我的同学很友善。"),
    "love": ("I love my family.", "我爱我的家人。"),
    "sport": ("My favorite sport is swimming.", "我最喜欢的运动是游泳。"),
    "only": ("I only have one pencil.", "我只有一支铅笔。"),
    "like": ("I like reading books.", "我喜欢读书。"),
    "don't": ("I don't like coffee.", "我不喜欢咖啡。"),
    "doesn't": ("He doesn't like math.", "他不喜欢数学。"),
    # ===== u06 =====
    "banana": ("I eat a banana for breakfast.", "我早餐吃一根香蕉。"),
    "hamburger": ("Hamburgers are delicious.", "汉堡包很好吃。"),
    "chicken": ("I like fried chicken.", "我喜欢炸鸡。"),
    "rice": ("We eat rice for lunch.", "我们午饭吃米饭。"),
    "carrot": ("Carrots are good for your eyes.", "胡萝卜对眼睛好。"),
    "tomato": ("Tomatoes are red and round.", "番茄又红又圆。"),
    "salad": ("I make a fruit salad.", "我做了一个水果沙拉。"),
    "strawberry": ("Strawberries are sweet.", "草莓很甜。"),
    "(u06) milk": ("I drink milk every morning.", "我每天早上喝牛奶。"),
    "bread": ("I have bread for breakfast.", "我早餐吃面包。"),
    "egg": ("I eat an egg every day.", "我每天吃一个鸡蛋。"),
    "apple": ("An apple a day keeps the doctor away.", "一天一苹果，医生远离我。"),
    "pear": ("The pear is yellow and sweet.", "梨是黄色的，很甜。"),
    "food": ("Chinese food is delicious.", "中国菜很好吃。"),
    "fruit": ("I like eating fruit.", "我喜欢吃水果。"),
    "vegetable": ("Eating vegetables is healthy.", "吃蔬菜很健康。"),
    "breakfast": ("I have breakfast at seven.", "我七点吃早餐。"),
    "lunch": ("We have lunch at school.", "我们在学校吃午餐。"),
    "dinner": ("My family has dinner together.", "我们一家人一起吃晚餐。"),
    "eat": ("Let's eat out today.", "我们今天出去吃吧。"),
    "really": ("I really like this song.", "我真的很喜欢这首歌。"),
    "want": ("I want a new bike.", "我想要一辆新自行车。"),
    "question": ("I have a question.", "我有一个问题。"),
    "star": ("My sister is a movie star.", "我姐姐是电影明星。"),
    "healthy": ("Eating well keeps you healthy.", "吃得好让你保持健康。"),
    # ===== u07 =====
    "much": ("How much is this T-shirt?", "这件T恤多少钱？"),
    "how much": ("How much are the shoes?", "这双鞋多少钱？"),
    "sock": ("I need a pair of socks.", "我需要一双袜子。"),
    "shirt": ("This shirt is too big.", "这件衬衫太大了。"),
    "T-shirt": ("I like your blue T-shirt.", "我喜欢你的蓝色T恤。"),
    "shorts": ("He wears shorts in summer.", "他夏天穿短裤。"),
    "sweater": ("Put on your sweater, it's cold.", "穿上毛衣，天气冷。"),
    "shoe": ("My shoes are new.", "我的鞋子是新的。"),
    "skirt": ("She has a beautiful skirt.", "她有一条漂亮的裙子。"),
    "dollar": ("This book is ten dollars.", "这本书十美元。"),
    "big": ("The box is big.", "这个盒子很大。"),
    "small": ("The cat is small.", "这只猫很小。"),
    "long": ("She has long hair.", "她有长头发。"),
    "short": ("He has short hair.", "他有短头发。"),
    "price": ("The price is very good.", "价格很好。"),
    "clothes": ("I like buying new clothes.", "我喜欢买新衣服。"),
    "store": ("The store sells many things.", "这家商店卖很多东西。"),
    "buy": ("I want to buy a gift.", "我想买一份礼物。"),
    "sell": ("The store sells fruits.", "这家商店卖水果。"),
    "all": ("All my friends are here.", "我所有的朋友都在这里。"),
    "need": ("I need a pen.", "我需要一支钢笔。"),
    "look": ("Look at the blackboard.", "看黑板。"),
    "pair": ("I need a pair of shoes.", "我需要一双鞋。"),
    "take": ("I will take this one.", "我要买这个。"),
    # ===== u08 =====
    "when": ("When is your birthday?", "你的生日是什么时候？"),
    "birthday": ("Happy birthday to you!", "祝你生日快乐！"),
    "month": ("There are twelve months in a year.", "一年有十二个月。"),
    "January": ("January is the first month.", "一月是第一个月。"),
    "February": ("February is very cold.", "二月很冷。"),
    "March": ("March comes after February.", "三月在二月之后。"),
    "April": ("April is warm and nice.", "四月温暖宜人。"),
    "May": ("I like May because of the flowers.", "我喜欢五月，因为花开。"),
    "June": ("June is my favorite month.", "六月是我最喜欢的月份。"),
    "July": ("We have summer vacation in July.", "我们七月放暑假。"),
    "August": ("August is very hot.", "八月很热。"),
    "September": ("School starts in September.", "学校九月开学。"),
    "October": ("October is a beautiful month.", "十月是美丽的月份。"),
    "November": ("November is cold.", "十一月很冷。"),
    "December": ("December is the last month.", "十二月是最后一个月。"),
    "happy": ("I am very happy today.", "我今天很开心。"),
    "old": ("I am twelve years old.", "我十二岁。"),
    "party": ("We have a birthday party.", "我们有一个生日聚会。"),
    "trip": ("We go on a school trip.", "我们去学校旅行。"),
    "art": ("I like art class.", "我喜欢美术课。"),
    "festival": ("Spring Festival is in January or February.", "春节在一月或二月。"),
    "test": ("We have a math test today.", "我们今天有数学考试。"),
    "game": ("I like playing computer games.", "我喜欢玩电脑游戏。"),
    "time": ("What time is it?", "几点了？"),
    "have a good time": ("Have a good time at the party!", "在聚会上玩得开心！"),
    # ===== u09 =====
    "subject": ("My favorite subject is English.", "我最喜欢的科目是英语。"),
    "science": ("I like science class.", "我喜欢科学课。"),
    "music": ("Music makes me happy.", "音乐让我开心。"),
    "math": ("Math is very useful.", "数学很有用。"),
    "Chinese": ("We study Chinese every day.", "我们每天学语文。"),
    "geography": ("Geography is interesting.", "地理很有趣。"),
    "history": ("I like learning about history.", "我喜欢学历史。"),
    "P.E.": ("P.E. class is fun.", "体育课很有趣。"),
    "because": ("I like it because it is fun.", "我喜欢它因为它很有趣。"),
    "Monday": ("Monday is the first day of the week.", "星期一是一周的第一天。"),
    "Tuesday": ("I have music class on Tuesday.", "我星期二有音乐课。"),
    "Wednesday": ("Wednesday is my busiest day.", "星期三是我最忙的一天。"),
    "Thursday": ("We have a test on Thursday.", "我们星期四有考试。"),
    "Friday": ("Friday is my favorite day.", "星期五是我最喜欢的一天。"),
    "Saturday": ("I play sports on Saturday.", "我星期六做运动。"),
    "Sunday": ("I visit my grandma on Sunday.", "我星期天去看望奶奶。"),
    "useful": ("English is very useful.", "英语很有用。"),
    "free": ("I am free this weekend.", "我这个周末有空。"),
    "cool": ("That's a cool car!", "那是一辆酷车！"),
    "finish": ("I finish my homework at eight.", "我八点完成作业。"),
    "lesson": ("I have four lessons in the morning.", "我上午有四节课。"),
    "hour": ("I study for an hour every day.", "我每天学习一小时。"),
    "favorite": ("My favorite color is blue.", "我最喜欢的颜色是蓝色。"),
    "why": ("Why do you like English?", "你为什么喜欢英语？"),
    # ===== b2u01 =====
    "violin": ("She plays the violin very well.", "她小提琴拉得很好。"),
    "drum": ("He plays the drum in the band.", "他在乐队里打鼓。"),
    "piano": ("I practice the piano every day.", "我每天练习钢琴。"),
    "also": ("I also like playing soccer.", "我也喜欢踢足球。"),
    "people": ("Many people like music.", "很多人喜欢音乐。"),
    "center": ("There is a sports center near my home.", "我家附近有一个体育中心。"),
    "home": ("I go home at five.", "我五点回家。"),
    "make": ("I make a model plane.", "我做了一个飞机模型。"),
    "today": ("What day is it today?", "今天星期几？"),
    "join": ("I want to join the music club.", "我想加入音乐俱乐部。"),
    "club": ("Our school has a chess club.", "我们学校有国际象棋俱乐部。"),
    "be good at": ("She is good at dancing.", "她擅长跳舞。"),
    "tell": ("Please tell me a story.", "请给我讲个故事。"),
    "talk": ("We talk about our day.", "我们谈论一天的生活。"),
    "kid": ("The kids are playing outside.", "孩子们在外面玩。"),
    # ===== b2u02 =====
    "get up": ("I get up at six every morning.", "我每天早上六点起床。"),
    "dress": ("I dress myself every morning.", "我每天早上自己穿衣服。"),
    "get dressed": ("Please get dressed quickly.", "请快点穿好衣服。"),
    "brush": ("I brush my teeth twice a day.", "我每天刷牙两次。"),
    "tooth": ("I have a toothache.", "我牙疼。"),
    "shower": ("I take a shower every morning.", "我每天早上洗淋浴。"),
    "take a shower": ("He takes a shower after sports.", "他运动后洗淋浴。"),
    "usually": ("I usually walk to school.", "我通常走路去学校。"),
    "never": ("I never eat junk food.", "我从不吃垃圾食品。"),
    "early": ("I get up early every day.", "我每天早起。"),
    "job": ("My father has a good job.", "我爸爸有一份好工作。"),
    "work": ("My mom goes to work at eight.", "我妈妈八点去上班。"),
    "station": ("The bus station is near here.", "公共汽车站在这附近。"),
    "night": ("I do my homework at night.", "我晚上做作业。"),
    "funny": ("The story is very funny.", "这个故事很有趣。"),
    "exercise": ("I exercise every morning.", "我每天早上锻炼。"),
    "group": ("We study in a group.", "我们小组学习。"),
    "half": ("I get up at half past six.", "我六点半起床。"),
    "quarter": ("It is a quarter to seven.", "现在是七点差一刻。"),
    # ===== b2u03 =====
    "train": ("I go to school by train.", "我坐火车去上学。"),
    "bus": ("I take the bus to school.", "我坐公共汽车去上学。"),
    "subway": ("He goes to work by subway.", "他坐地铁去上班。"),
    "ride": ("I ride my bike to school.", "我骑自行车去学校。"),
    "bike": ("My bike is blue.", "我的自行车是蓝色的。"),
    "drive": ("My dad drives me to school.", "我爸爸开车送我去学校。"),
    "car": ("We go to the park by car.", "我们开车去公园。"),
    "live": ("I live near my school.", "我住在学校附近。"),
    "stop": ("The bus stop is over there.", "公共汽车站在那边。"),
    "cross": ("Please cross the road carefully.", "请小心过马路。"),
    "river": ("There is a river near my home.", "我家附近有一条河。"),
    "many": ("There are many books in the library.", "图书馆里有很多书。"),
    "village": ("My grandparents live in a small village.", "我的祖父母住在一个小村庄。"),
    "between": ("The park is between the school and the hospital.", "公园在学校和医院之间。"),
    "bridge": ("There is a bridge over the river.", "河上有座桥。"),
    "boat": ("We take a boat on the lake.", "我们在湖上划船。"),
    "year": ("I am thirteen years old.", "我十三岁。"),
    "afraid": ("Don't be afraid. I am here.", "别害怕，我在这里。"),
    "leave": ("I leave home at seven.", "我七点离开家。"),
    "dream": ("I have a dream to be a teacher.", "我有一个当老师的梦想。"),
    "true": ("I hope my dream comes true.", "我希望我的梦想成真。"),
    "come true": ("My dream comes true.", "我的梦想实现了。"),
    "kilometer": ("My school is two kilometers away.", "我的学校在两公里外。"),
    "new": ("I have a new schoolbag.", "我有一个新书包。"),
    "every": ("I go to school every day.", "我每天都去上学。"),
    # ===== b2u04 =====
    "rule": ("We must follow the school rules.", "我们必须遵守校规。"),
    "arrive": ("I arrive at school at eight.", "我八点到校。"),
    "hallway": ("Don't run in the hallway.", "不要在走廊里跑。"),
    "listen": ("Please listen to the teacher.", "请听老师讲。"),
    "fight": ("Don't fight with your classmates.", "不要和同学打架。"),
    "outside": ("Let's play outside.", "我们去外面玩吧。"),
    "wear": ("We must wear our school uniforms.", "我们必须穿校服。"),
    "important": ("It is important to study hard.", "努力学习很重要。"),
    "bring": ("Please bring your book to class.", "请把书带来上课。"),
    "have to": ("I have to finish my homework.", "我必须完成作业。"),
    "uniform": ("Our school uniform is blue and white.", "我们的校服是蓝白色的。"),
    "quiet": ("Please be quiet in the library.", "请在图书馆保持安静。"),
    "noisy": ("The classroom is too noisy.", "教室太吵了。"),
    "relax": ("I relax by listening to music.", "我通过听音乐放松。"),
    "read": ("I like reading storybooks.", "我喜欢读故事书。"),
    "dirty": ("My shoes are dirty.", "我的鞋子脏了。"),
    "kitchen": ("Mom is cooking in the kitchen.", "妈妈在厨房做饭。"),
    "more": ("I want to learn more English.", "我想学更多英语。"),
    "feel": ("I feel happy today.", "我今天感到开心。"),
    "strict": ("Our teacher is strict but nice.", "我们的老师严格但很好。"),
    "remember": ("Please remember to bring your homework.", "请记得带作业。"),
    "follow": ("Please follow the rules.", "请遵守规则。"),
    "luck": ("Good luck to you!", "祝你好运！"),
    "keep": ("Please keep your room clean.", "请保持房间干净。"),
    "hair": ("She has long black hair.", "她有黑色长发。"),
    "learn": ("I learn English at school.", "我在学校学英语。"),
    # ===== b2u05 =====
    "panda": ("Pandas are black and white.", "熊猫是黑白相间的。"),
    "zoo": ("We go to the zoo on Sunday.", "我们星期天去动物园。"),
    "tiger": ("Tigers are very strong.", "老虎很强壮。"),
    "elephant": ("Elephants have big ears.", "大象有大耳朵。"),
    "koala": ("Koalas are very cute.", "考拉很可爱。"),
    "lion": ("The lion is the king of animals.", "狮子是百兽之王。"),
    "giraffe": ("Giraffes have long necks.", "长颈鹿有长脖子。"),
    "animal": ("I like all kinds of animals.", "我喜欢各种动物。"),
    "cute": ("The baby panda is very cute.", "熊猫宝宝很可爱。"),
    "lazy": ("My cat is very lazy.", "我的猫很懒。"),
    "smart": ("Dolphins are very smart.", "海豚很聪明。"),
    "beautiful": ("The flowers are beautiful.", "花很漂亮。"),
    "scary": ("Lions look scary.", "狮子看起来很吓人。"),
    "kind": ("What kind of animal is this?", "这是什么动物？"),
    "kind of": ("Koalas are kind of cute.", "考拉有点可爱。"),
    "Australia": ("Koalas come from Australia.", "考拉来自澳大利亚。"),
    "south": ("Guangzhou is in the south of China.", "广州在中国南方。"),
    "Africa": ("Elephants live in Africa.", "大象生活在非洲。"),
    "pet": ("I have a pet dog.", "我有一只宠物狗。"),
    "leg": ("The cat has four legs.", "猫有四条腿。"),
    "cat": ("My cat likes to sleep.", "我的猫喜欢睡觉。"),
    "sleep": ("I sleep for eight hours every night.", "我每晚睡八小时。"),
    "friendly": ("My dog is very friendly.", "我的狗很友善。"),
    "shy": ("The girl is a little shy.", "那个女孩有点害羞。"),
    "save": ("We should save the animals.", "我们应该拯救动物。"),
    "symbol": ("The dove is a symbol of peace.", "鸽子是和平的象征。"),
    "flag": ("The flag of China is red.", "中国的国旗是红色的。"),
    "forget": ("Don't forget your homework.", "别忘了你的作业。"),
    "danger": ("Tigers are in danger.", "老虎处于危险中。"),
    "cut": ("Please cut the paper.", "请剪纸。"),
    "kill": ("Don't kill the animals.", "不要杀害动物。"),
    # ===== b2u06 =====
    "newspaper": ("My dad reads the newspaper every morning.", "我爸爸每天早上看报纸。"),
    "use": ("Can I use your pen?", "我可以用你的钢笔吗？"),
    "soup": ("I like drinking soup.", "我喜欢喝汤。"),
    "wash": ("I wash my hands before dinner.", "我饭前洗手。"),
    "movie": ("I watch a movie on weekends.", "我周末看电影。"),
    "house": ("Our house is big and clean.", "我们的房子又大又干净。"),
    "drink": ("I drink milk every day.", "我每天都喝牛奶。"),
    "tea": ("My grandpa likes green tea.", "我爷爷喜欢绿茶。"),
    "tomorrow": ("Tomorrow is Saturday.", "明天是星期六。"),
    "pool": ("We swim in the pool.", "我们在游泳池游泳。"),
    "shop": ("I shop with my mom on weekends.", "我周末和妈妈购物。"),
    "man": ("The man in blue is my uncle.", "穿蓝衣服的男人是我叔叔。"),
    "study": ("I study in my room.", "我在房间学习。"),
    "miss": ("I miss my family when I am at school.", "我在学校时想念家人。"),
    "wish": ("I wish you a happy birthday.", "我祝你生日快乐。"),
    "delicious": ("The food is delicious.", "食物很美味。"),
    "child": ("The children are playing outside.", "孩子们在外面玩。"),
    "race": ("He wins the running race.", "他赢了赛跑。"),
    "host": ("The host welcomes us.", "主人欢迎我们。"),
    "young": ("My teacher is young and beautiful.", "我的老师年轻漂亮。"),
    # ===== b2u07 =====
    "rain": ("It often rains in spring.", "春天经常下雨。"),
    "windy": ("It is very windy today.", "今天风很大。"),
    "cloudy": ("It is cloudy today.", "今天是多云。"),
    "sunny": ("It is sunny and warm.", "天气晴朗温暖。"),
    "snow": ("It snows in winter.", "冬天下雪。"),
    "weather": ("The weather is nice today.", "今天天气很好。"),
    "cold": ("It is cold outside. Put on your coat.", "外面冷，穿上外套。"),
    "hot": ("It is very hot in summer.", "夏天很热。"),
    "warm": ("Spring is warm.", "春天很温暖。"),
    "dry": ("The weather is dry in autumn.", "秋天天气干燥。"),
    "summer": ("I like swimming in summer.", "我喜欢夏天游泳。"),
    "winter": ("It is cold in winter.", "冬天很冷。"),
    "spring": ("Spring is a beautiful season.", "春天是一个美丽的季节。"),
    "autumn": ("Leaves turn yellow in autumn.", "秋天叶子变黄。"),
    "season": ("My favorite season is summer.", "我最喜欢的季节是夏天。"),
    "vacation": ("We go on vacation in July.", "我们七月去度假。"),
    "visit": ("I visit my grandparents on weekends.", "我周末去看望祖父母。"),
    "Canada": ("My uncle lives in Canada.", "我叔叔住在加拿大。"),
    "Europe": ("I want to travel to Europe.", "我想去欧洲旅行。"),
    "mountain": ("We climb the mountain on Sunday.", "我们星期天去爬山。"),
    "ski": ("I like skiing in winter.", "我喜欢冬天滑雪。"),
    "country": ("China is a big country.", "中国是一个大国。"),
    # ===== b2u08 =====
    "post": ("I go to the post office to send a letter.", "我去邮局寄信。"),
    "post office": ("The post office is on Green Street.", "邮局在格林街。"),
    "police": ("The police officer helps us.", "警察帮助我们。"),
    "hotel": ("We stay in a hotel during the trip.", "旅行期间我们住在酒店。"),
    "restaurant": ("We eat dinner at a restaurant.", "我们在餐馆吃晚餐。"),
    "bank": ("My mother works in a bank.", "我妈妈在银行工作。"),
    "hospital": ("The hospital is near my home.", "医院在我家附近。"),
    "street": ("The bookstore is on Main Street.", "书店在主街上。"),
    "near": ("There is a park near my school.", "我们学校附近有一个公园。"),
    "across": ("The bank is across the street.", "银行在街对面。"),
    "across from": ("The library is across from the school.", "图书馆在学校对面。"),
    "front": ("Please stand in front of the class.", "请站在全班前面。"),
    "in front of": ("The teacher stands in front of the blackboard.", "老师站在黑板前。"),
    "behind": ("The cat is behind the door.", "猫在门后面。"),
    "town": ("I live in a small town.", "我住在一个小镇上。"),
    "around": ("Let's walk around the park.", "我们绕着公园走走吧。"),
    "north": ("Beijing is in the north of China.", "北京在中国北方。"),
    "along": ("Walk along this street, and you will see it.", "沿着这条街走，你就会看到它。"),
    "turn": ("Turn left at the corner.", "在拐角处左转。"),
    "right": ("Turn right at the traffic lights.", "在红绿灯处右转。"),
    "left": ("The school is on your left.", "学校在你的左边。"),
    "crossing": ("Turn left at the first crossing.", "在第一个十字路口左转。"),
    "neighborhood": ("There is a park in my neighborhood.", "我家附近有一个公园。"),
    "spend": ("I spend two hours on homework.", "我花两个小时做作业。"),
    "climb": ("The cat climbs up the tree.", "猫爬上了树。"),
    "enjoy": ("I enjoy reading books.", "我喜欢读书。"),
    "money": ("I save my money in a piggy bank.", "我把钱存在存钱罐里。"),
    # ===== b2u09 =====
    "curly": ("She has short curly hair.", "她有短卷发。"),
    "straight": ("He has straight brown hair.", "他有棕色直发。"),
    "tall": ("My brother is tall and thin.", "我哥哥又高又瘦。"),
    "medium": ("She is of medium height.", "她中等身高。"),
    "height": ("What is your height?", "你多高？"),
    "thin": ("She is thin and beautiful.", "她又瘦又漂亮。"),
    "heavy": ("My uncle is a little heavy.", "我叔叔有点胖。"),
    "build": ("He has a strong build.", "他体格强壮。"),
    "glasses": ("My teacher wears glasses.", "我的老师戴眼镜。"),
    "blonde": ("She has long blonde hair.", "她有金色长发。"),
    "mouth": ("Open your mouth, please.", "请张嘴。"),
    "face": ("She has a round face.", "她有一张圆脸。"),
    "eye": ("She has big blue eyes.", "她有大大的蓝眼睛。"),
    "nose": ("The elephant has a long nose.", "大象有长鼻子。"),
    "ear": ("My ears are small.", "我的耳朵很小。"),
    "singer": ("I want to be a singer.", "我想成为歌手。"),
    "artist": ("The artist draws beautiful pictures.", "艺术家画漂亮的画。"),
    "person": ("She is a kind person.", "她是一个善良的人。"),
    "hand": ("Please raise your hand.", "请举手。"),
    "arm": ("My mother has a baby in her arms.", "妈妈怀里抱着婴儿。"),
    "end": ("The street ends here.", "街道在这里结束。"),
    "real": ("Is this a real story?", "这是一个真实的故事吗？"),
    "each": ("Each student has a book.", "每个学生都有一本书。"),
    "way": ("This is the way to school.", "这是去学校的路。"),
    "different": ("We are in different classes.", "我们在不同的班级。"),
    "describe": ("Can you describe your friend?", "你能描述一下你的朋友吗？"),
    # ===== b2u10 =====
    "noodle": ("I like eating noodles for breakfast.", "我喜欢早餐吃面条。"),
    "mutton": ("I like mutton soup.", "我喜欢羊肉汤。"),
    "beef": ("Beef noodles are delicious.", "牛肉面很好吃。"),
    "cabbage": ("Cabbage is good for your health.", "卷心菜对健康有好处。"),
    "potato": ("I like eating potatoes.", "我喜欢吃土豆。"),
    "special": ("Today's special is beef noodles.", "今天的特色菜是牛肉面。"),
    "size": ("What size do you want?", "你想要什么尺寸？"),
    "bowl": ("I have a bowl of rice.", "我吃了一碗米饭。"),
    "would": ("Would you like some tea?", "你想喝点茶吗？"),
    "tofu": ("Tofu is healthy and delicious.", "豆腐又健康又好吃。"),
    "large": ("I want a large bowl of noodles.", "我要一大碗面。"),
    "order": ("May I order now?", "我现在可以点餐吗？"),
    "answer": ("Please answer the question.", "请回答问题。"),
    "cake": ("I like chocolate cake.", "我喜欢巧克力蛋糕。"),
    "candle": ("We light the candles on the birthday cake.", "我们点燃生日蛋糕上的蜡烛。"),
    "age": ("My age is thirteen.", "我十三岁。"),
    "blow": ("Please blow out the candles.", "请吹灭蜡烛。"),
    "blow out": ("Make a wish and blow out the candles.", "许个愿，吹灭蜡烛。"),
    "if": ("If you are tired, have a rest.", "如果你累了，就休息一下。"),
    "will": ("I will go to Beijing next week.", "我下周要去北京。"),
    "idea": ("That's a good idea!", "好主意！"),
    # ===== b2u11 =====
    "(b2u11) milk": ("The farmer milks the cow every morning.", "农夫每天早上挤牛奶。"),
    "cow": ("The cow gives us milk.", "奶牛给我们提供牛奶。"),
    "horse": ("I can ride a horse.", "我会骑马。"),
    "chicken": ("The chicken is on the farm.", "鸡在农场里。"),
    "farm": ("We visit a farm on the weekend.", "我们周末去参观农场。"),
    "guide": ("The guide shows us around.", "导游带我们参观。"),
    "gift": ("I buy a gift for my mother.", "我给妈妈买了一件礼物。"),
    "excellent": ("Your English is excellent!", "你的英语很棒！"),
    "yesterday": ("I went to the park yesterday.", "我昨天去了公园。"),
    "flower": ("The flowers are beautiful in spring.", "春天的花很美。"),
    "worry": ("Don't worry, I can help you.", "别担心，我能帮你。"),
    "museum": ("We visit the science museum.", "我们参观科学博物馆。"),
    "fire": ("Fire is very hot.", "火很热。"),
    "fire station": ("The fire station is on Green Street.", "消防站在格林街。"),
    "painting": ("I like the painting on the wall.", "我喜欢墙上的画。"),
    "sun": ("The sun rises in the east.", "太阳从东方升起。"),
    "pick": ("We pick apples from the tree.", "我们从树上摘苹果。"),
    "grow": ("The flowers grow in spring.", "花在春天生长。"),
    "quite": ("This book is quite interesting.", "这本书相当有趣。"),
    "lovely": ("What a lovely baby!", "多可爱的宝宝！"),
    "expensive": ("The car is too expensive.", "这辆车太贵了。"),
    "cheap": ("This pen is very cheap.", "这支钢笔很便宜。"),
    "slow": ("The old man walks slow.", "老人走得很慢。"),
    "fast": ("The train is very fast.", "火车很快。"),
    "sound": ("That sounds like a good idea.", "那听起来是个好主意。"),
    "all in all": ("All in all, it was a great trip.", "总的来说，这是一次很棒的旅行。"),
    # ===== b2u12 =====
    "camp": ("We go camping in the forest.", "我们去森林里露营。"),
    "lake": ("There is a lake in the park.", "公园里有一个湖。"),
    "beach": ("We play on the beach.", "我们在海滩上玩。"),
    "sheep": ("There are three sheep on the farm.", "农场里有三只羊。"),
    "natural": ("This park has beautiful natural scenery.", "这个公园有美丽的自然风光。"),
    "butterfly": ("Butterflies are colorful.", "蝴蝶五颜六色。"),
    "visitor": ("Many visitors come to the museum.", "许多游客来博物馆参观。"),
    "tired": ("I am tired after the long walk.", "走了一段长路后我累了。"),
    "stay": ("I stay at home on rainy days.", "下雨天我待在家里。"),
    "stay up late": ("Don't stay up late.", "不要熬夜。"),
    "away": ("He lives far away from school.", "他住得离学校很远。"),
    "run away": ("The cat runs away from the dog.", "猫从狗身边跑开了。"),
    "mouse": ("The mouse is small and fast.", "老鼠又小又快。"),
    "baby": ("The baby is sleeping.", "宝宝在睡觉。"),
    "shout": ("Don't shout in the classroom.", "不要在教室里大喊。"),
    "language": ("I learn a new language.", "我学一门新语言。"),
    "fly": ("The bird can fly high.", "鸟可以飞得很高。"),
    "kite": ("We fly a kite in the park.", "我们在公园放风筝。"),
    "high": ("The plane is flying high in the sky.", "飞机在高空飞行。"),
    "ago": ("I visited Beijing two years ago.", "我两年前去过北京。"),
    "India": ("India has many elephants.", "印度有很多大象。"),
    "move": ("My family moves to a new house.", "我家搬到了新房子。"),
    "start": ("School starts at eight.", "学校八点开始上课。"),
    "jump": ("The rabbit jumps very high.", "兔子跳得很高。"),
    "wake": ("I wake up at six every morning.", "我每天早上六点醒来。"),
    "wake up": ("Please wake me up at seven.", "请七点叫醒我。"),
    "into": ("The cat goes into the box.", "猫进了盒子。"),
    "as": ("I work as a volunteer.", "我作为一名志愿者工作。"),
    "scared": ("I am scared of the dark.", "我害怕黑暗。"),
}

def main():
    supp = json.loads(SUPP_PATH.read_text(encoding="utf-8"))
    count = 0
    for unit, words in supp.items():
        for w in words:
            if "ex" in w:
                continue
            unit_key = f"({unit}) {w['w']}"
            key = w["w"]
            if unit_key in SENTENCES:
                w["ex"] = SENTENCES[unit_key][0]
                w["trans"] = SENTENCES[unit_key][1]
                count += 1
            elif key in SENTENCES:
                w["ex"] = SENTENCES[key][0]
                w["trans"] = SENTENCES[key][1]
                count += 1
    SUPP_PATH.write_text(json.dumps(supp, ensure_ascii=False, indent=2), encoding="utf-8")
    total = sum(len(ws) for ws in supp.values())
    print(f"Added sentences to {count}/{total} words in vocab-supplement.json")

if __name__ == "__main__":
    main()
