#!/usr/bin/env python3
"""Grade 8上册 (8 units) teaching content data."""

U = lambda u: UNITS_8A[u]  # noqa

UNITS_8A = {
    "u01": {
        "num": "U1", "title": "Happy Holiday!", "topic": "假期活动",
        "en_topic": "Holiday Plans & Experiences", "functions": "Talk about holiday plans and past experiences",
        "grammar": "一般过去时复习 · be going to 将来时 · wh-疑问句",
        "writing": "My Holiday Plan",
        "can_do": ["能用 be going to 谈论假期计划","能用一般过去时描述假期经历","能就 holiday 话题进行 wh- 问答","能写一篇假期计划短文"],
        "dialogue_scene": "开学后，同学们互相分享暑假经历并讨论即将到来的国庆假期计划。",
        "dialogue": [
            ("Li Hua", "Hi, Mike! How was your summer vacation?", "嗨，Mike！暑假过得怎么样？"),
            ("Mike", "It was wonderful! I went to Beijing with my family.", "棒极了！我和家人去了北京。"),
            ("Li Hua", "Sounds great! What did you do there?", "听起来不错！你们在那里做了什么？"),
            ("Mike", "We visited the Great Wall and ate Beijing duck. What about you?", "我们参观了长城，还吃了北京烤鸭。你呢？"),
            ("Li Hua", "I stayed at home and practiced English every day. I'm going to improve my speaking this term.", "我待在家里每天练英语。这学期我打算提高口语。"),
            ("Mike", "That's a good plan! What are you going to do for National Day?", "好计划！你国庆节打算做什么？"),
            ("Li Hua", "I'm going to visit my grandparents in the countryside. I'm going to help them with the farm work.", "我打算去乡下看望爷爷奶奶，帮他们干农活。"),
            ("Mike", "That sounds meaningful. I'm going to take a short trip to Hangzhou with my cousins.", "听起来很有意义。我打算和表弟表妹去杭州短途旅行。"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>How was your summer vacation?</em> → 询问过去经历，用一般过去时。回答用 <strong>It was + adj.</strong>",
            "<strong>2.</strong> <em>What did you do there?</em> → 一般过去时的特殊疑问句：<strong>What + did + 主语 + do?</strong>",
            "<strong>3.</strong> <em>I'm going to improve my speaking.</em> → <strong>be going to + 动词原形</strong> 表示打算/计划做某事。",
            "<strong>4.</strong> <em>What are you going to do for National Day?</em> → be going to 的特殊疑问句：<strong>What + be + 主语 + going to do?</strong>",
            "<strong>5.</strong> <em>That sounds meaningful.</em> → sound（听起来）+ adj.，类似的还有 look（看起来）、taste（尝起来）、feel（感觉）。",
        ],
        "vocab": [
            ("vacation","veɪˈkeɪʃn","n.","假期","I had a wonderful vacation in Beijing.","我在北京度过了一个愉快的假期。"),
            ("holiday","ˈhɒlədeɪ","n.","假日","What are you going to do for the holiday?","你假期打算做什么？"),
            ("practice","ˈpræktɪs","v.","练习","I practice English every morning.","我每天早上练习英语。"),
            ("improve","ɪmˈpruːv","v.","提高","I want to improve my speaking skills.","我想提高口语能力。"),
            ("meaningful","ˈmiːnɪŋfl","adj.","有意义的","Helping others is meaningful.","帮助别人很有意义。"),
            ("countryside","ˈkʌntrisaɪd","n.","乡下","My grandparents live in the countryside.","我爷爷奶奶住在乡下。"),
            ("visit","ˈvɪzɪt","v.","拜访；参观","We visited the Great Wall last week.","我们上周参观了长城。"),
            ("plan","plæn","n./v.","计划","Do you have any plans for the weekend?","你周末有什么计划吗？"),
            ("trip","trɪp","n.","旅行","We're going to take a trip to Sanya.","我们打算去三亚旅行。"),
            ("experience","ɪkˈspɪriəns","n./v.","经历","Traveling gives me new experiences.","旅行带给我新的体验。"),
            ("improvement","ɪmˈpruːvmənt","n.","提高；进步","I can see improvement in my English.","我能看到英语的进步。"),
            ("relax","rɪˈlæks","v.","放松","I like to relax by listening to music.","我喜欢听音乐放松。"),
        ],
        "patterns": [
            ("How was your…?", "询问过去经历", "How was <span class=\"slot\">your summer vacation</span>? — It was <span class=\"slot\">wonderful</span>."),
            ("be going to + do", "表示计划打算", "I <span class=\"slot\">am going to</span> <span class=\"slot\">visit my grandparents</span>."),
            ("What did you do?", "询问过去具体行为", "<strong>What did</strong> you <strong>do</strong> <span class=\"slot\">last weekend</span>? — I <span class=\"slot\">visited the museum</span>."),
            ("That sounds + adj.", "表达对某事的评价", "That sounds <span class=\"slot\">great</span>! / That sounds <span class=\"slot\">meaningful</span>."),
        ],
        "grammar_title": "一般过去时 & be going to 将来时",
        "grammar_sections": [
            ("一般过去时——规则动词变化", [
                ("构成规则","示例","变化"),
                ("一般情况 +ed","play → played","work → worked"),
                ("以 e 结尾 +d","like → liked","live → lived"),
                ("辅音+y 变 ied","study → studied","try → tried"),
                ("重读闭音节双写+ed","stop → stopped","plan → planned"),
            ]),
            ("be going to 结构", [
                ("人称","肯定句","疑问句"),
                ("I","I am going to + v.","Am I going to + v.?"),
                ("He/She/It","He is going to + v.","Is he going to + v.?"),
                ("We/You/They","They are going to + v.","Are they going to + v.?"),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong wotd-say" data-speak="I go to Beijing last week.">I go to Beijing last week.</span>（一般过去时需用 went）',
            '✅ <span class="correct wotd-say" data-speak="I went to Beijing last week.">I went to Beijing last week.</span>',
            '❌ <span class="wrong wotd-say" data-speak="I am go to visit my grandparents.">I am go to visit my grandparents.</span>（be going to 后动词用原形）',
            '✅ <span class="correct wotd-say" data-speak="I am going to visit my grandparents.">I am going to visit my grandparents.</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[go] I ____ to the park yesterday.","went"),
            ("基础","★☆☆","[be] She ____ at home last Sunday.","was"),
            ("基础","★☆☆","[be going to] They ____ going to visit the museum tomorrow.","are"),
        ],
        "mid_qs": [
            ("提升","★★☆","改错：I am going to visited my uncle.","I am going to visit my uncle."),
            ("提升","★★☆","连词成句：what / do / you / last weekend / did / ?","What did you do last weekend?"),
            ("提升","★★☆","用所给词填空：How ____ (be) your trip? — It ____ (be) exciting.","was; was"),
        ],
        "hard_qs": [
            ("挑战","★★★","汉译英：你打算怎样提高你的英语？","How are you going to improve your English?"),
            ("挑战","★★★","补全对话：<br>A: I had a great holiday!<br>B: Really? ____ ____ you ____?<br>A: I ____ (go) to the beach.","What did do / went"),
            ("挑战","★★★","用 5 句话描述你上个假期和下个假期的计划。","（自由发挥）"),
        ],
        "reading_title": "Holidays Around the World",
        "reading_text": [
            "People around the world celebrate holidays in different ways.",
            "In China, the Spring Festival is the most important holiday. Families get together, eat dumplings, and watch the Spring Festival Gala. Many children get red packets from their elders.",
            "In the United States, Thanksgiving is a time for family reunions. People eat turkey, mashed potatoes, and pumpkin pie.",
            "No matter where you are, holidays are a time to relax, have fun, and be with the people you love.",
        ],
        "reading_gloss": [("gala","n. 文艺晚会"),("reunion","n. 团聚"),("turkey","n. 火鸡"),("mashed potatoes","n. 土豆泥"),("pumpkin pie","n. 南瓜派")],
        "reading_qs": [
            ("阅读","★★☆","1. Which holiday is most important in China?","The Spring Festival."),
            ("阅读","★★☆","2. What do Americans eat on Thanksgiving?","Turkey, mashed potatoes, and pumpkin pie."),
            ("阅读","★★★","3. What do all holidays have in common?","A time to relax, have fun, and be with loved ones."),
        ],
        "exam_q_type": "完形填空", "exam_q": "阅读下面短文，选择最佳选项填入空白处。",
        "exam_passage": ["Last summer, I (1)____ to Qingdao with my parents. We (2)____ there by train. The weather was sunny. We (3)____ on the beach and swam. We also (4)____ fresh seafood. Next year, I (5)____ going to visit again!"],
        "exam_options": [
            ("1.",{"A":"go","B":"went","C":"going","D":"goes"}),
            ("2.",{"A":"get","B":"got","C":"gets","D":"getting"}),
            ("3.",{"A":"relax","B":"relaxed","C":"relaxing","D":"relaxes"}),
            ("4.",{"A":"eat","B":"eats","C":"ate","D":"eating"}),
            ("5.",{"A":"am","B":"is","C":"are","D":"be"}),
        ],
        "exam_answers": ["B (went)","B (got)","B (relaxed)","C (ate)","A (am)"],
        "writing_prompt": '请以 "My Summer Holiday Plan" 为题，写一篇 60-80 词的短文。',
        "writing_framework": ["开头：引出话题——暑假即将到来。","主体：具体计划——去哪里？做什么？和谁一起？","结尾：表达期待和心情。"],
        "writing_model_en": "Summer holiday is coming. I'm going to visit my grandparents in the countryside. I'm going to help them with farm work every morning. In the afternoon, I'm going to read books and practice English. I think it will be a meaningful holiday. I'm looking forward to it!",
        "writing_model_cn": "暑假快到了。我打算去乡下看望爷爷奶奶，每天早上帮他们干农活，下午看书练英语。这将是一个有意义的假期。",
        "project_title": "My Holiday Dream Board",
        "project_desc": "设计一张\"假期愿景板\"(Dream Board)，用英语和图片展示你最想去的三个地方及理由。",
        "project_steps": ["选择一个梦想的目的地。","写出理由（至少 3 句话）。","用 be going to 写出计划。","配上图片做成 A4 展示板。","在班里做 1 分钟展示。"],
        "project_rubric": ["内容丰富度","语言准确性：be going to 和一般过去时","创意与美观","口语表达"],
        "checklist": ["我能用 be going to 谈论假期计划","我能用一般过去时描述经历","我能区分 be going to 和 will","我能写 60 词以上假期计划"],
        "feynman": "假装你是旅游博主，用英语介绍上假期的经历和下次假期的计划。练习一般过去时和 be going to。",
        "review": ["用 be going to 写 5 个计划句","写出 10 个不规则动词过去式","写一段 80 词假期回忆","复习 be going to 疑问句结构"],
        "next_unit_title": "How often do you exercise?",
        "next_unit_desc": "下一单元你将学习频率副词（always/usually/often/sometimes/never）谈论生活习惯。",
    },

    "u02": {
        "num": "U2", "title": "How often do you exercise?", "topic": "生活习惯",
        "en_topic": "Daily Habits & Free Time Activities",
        "functions": "Talk about how often you do things",
        "grammar": "频率副词（always/usually/often/sometimes/never）· How often 疑问句",
        "writing": "My Healthy Habit Report",
        "can_do": ["能用 How often 询问频率","能用频率副词描述日常习惯","能做简单的健康习惯调查并汇报","能用百分比表达频率"],
        "dialogue_scene": "老师让同学们互相采访各自的课外活动频率。",
        "dialogue": [
            ("Claire","Hi, Tom! How often do you exercise?","嗨 Tom！你多久锻炼一次？"),
            ("Tom","I exercise every day. I run for 30 minutes in the morning.","我每天锻炼。早上跑 30 分钟步。"),
            ("Claire","Great! How often do you watch TV?","很好！你看电视的频率呢？"),
            ("Tom","I hardly ever watch TV. I'm too busy with homework.","我几乎不看电视，作业太忙了。"),
            ("Claire","What about reading?","那阅读呢？"),
            ("Tom","I often read books before bed. I read about two books a month.","我经常睡前看书，一个月大概读两本。"),
            ("Claire","You have good habits! I always stay up late. I need to change.","你习惯真好！我总是熬夜，得改改。"),
            ("Tom","How often do you stay up late?","你多久熬夜一次？"),
            ("Claire","Almost every day. I'm going to go to bed earlier from next week.","几乎每天都熬。我打算下周起早点睡。"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>How often do you exercise?</em> → <strong>How often</strong> 问频率，回答用频率副词或次数表达。",
            "<strong>2.</strong> 频率副词顺序：<strong>always(100%) > usually(80%) > often(60%) > sometimes(40%) > hardly ever(5%) > never(0%)</strong>",
            "<strong>3.</strong> <em>I hardly ever watch TV.</em> → <strong>hardly ever</strong> 表示\"几乎不\"，含否定意义。",
            "<strong>4.</strong> <em>I read about two books a month.</em> → <strong>次数 + a + 时间单位</strong>：once a week / twice a month / three times a year",
        ],
        "vocab": [
            ("exercise","ˈeksərsaɪz","v./n.","锻炼；运动","How often do you exercise?","你多久锻炼一次？"),
            ("hardly","ˈhɑːrdli","adv.","几乎不","I hardly ever go to the cinema.","我几乎不去电影院。"),
            ("ever","ˈevər","adv.","曾经；在任何时候","Hardly ever means almost never.","Hardly ever 意为几乎从不。"),
            ("once","wʌns","adv.","一次；曾经","I go to the library once a week.","我每周去一次图书馆。"),
            ("twice","twaɪs","adv.","两次；两倍","She reads English twice a day.","她每天读两次英语。"),
            ("program","ˈproʊɡræm","n.","节目；项目","What's your favorite TV program?","你最喜欢的电视节目是什么？"),
            ("full","fʊl","adj.","满的；充满的","My weekend is full of activities.","我的周末排满了活动。"),
            ("maybe","ˈmeɪbi","adv.","也许；大概","Maybe I can join you tomorrow.","也许我明天可以加入你。"),
            ("least","liːst","adj./adv.","最少；最小","You should exercise at least three times a week.","你应该至少每周锻炼三次。"),
            ("result","rɪˈzʌlt","n.","结果；成绩","Here are the results of the survey.","这是调查结果。"),
            ("percent","pərˈsent","n.","百分之…","Forty percent of students exercise every day.","40% 的学生每天锻炼。"),
            ("habit","ˈhæbɪt","n.","习惯","Good habits help us stay healthy.","好习惯帮助我们保持健康。"),
        ],
        "patterns": [
            ("How often + 一般疑问句?", "询问频率", "How often <span class=\"slot\">do you exercise</span>? — <span class=\"slot\">Every day</span>."),
            ("频率副词 + 实义动词", "频率副词放在行为动词前", "I <span class=\"slot\">always</span> get up early. / She <span class=\"slot\">hardly ever</span> watches TV."),
            ("次数 + a + 时间单位", "表达频率数量", "<span class=\"slot\">Once</span> a week / <span class=\"slot\">Three times</span> a month."),
        ],
        "grammar_title": "频率副词 & How often 疑问句",
        "grammar_sections": [
            ("频率副词用法", [
                ("副词","频率","示例"),
                ("always","100%","I always brush my teeth."),
                ("usually","80%","I usually get up at 6:30."),
                ("often","60%","I often go to the park."),
                ("sometimes","40%","I sometimes watch TV."),
                ("hardly ever","5%","I hardly ever eat junk food."),
                ("never","0%","I never smoke."),
            ]),
            ("How often 疑问句结构", [
                ("结构","示例"),
                ("How often + do/does + 主语 + 动词?","How often do you read books?"),
                ("How often + be + 主语 + 形容词?","How often are you late for school?"),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="I every day exercise.">I every day exercise.</span>（频率词不放在句首/句末修饰动词）',
            '✅ <span class="correct" data-speak="I exercise every day.">I exercise every day.</span>',
            '❌ <span class="wrong" data-speak="How often you go shopping?">How often you go shopping?</span>（疑问句需助动词 do/does）',
            '✅ <span class="correct" data-speak="How often do you go shopping?">How often do you go shopping?</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[频率副词] She ____ (总是) gets up at 6 o'clock.","always"),
            ("基础","★☆☆","[How often] ____ ____ do you go to the library? — Twice a week.","How often"),
            ("基础","★☆☆","[选择] I have ____ (ever / never) been to Beijing. It's my first time.","never"),
        ],
        "mid_qs": [
            ("提升","★★☆","[排序] every / I / exercise / day / .","I exercise every day."),
            ("提升","★★☆","[改错] How often does he goes to the gym?","How often does he go to the gym?"),
            ("提升","★★☆","[填空] She ____ (几乎不) eats junk food, so she is very healthy.","hardly ever"),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 你多久看一次电影？— 我一个月看两次。","How often do you watch a movie? — I watch a movie twice a month."),
            ("挑战","★★★","[调查汇报] 请你写一段话描述你的锻炼习惯，至少用到 3 个频率词。","（自由发挥）"),
            ("挑战","★★★","[完形] I ____ (usual/usually) get up at 7, but I ____ (hard/hardly) ever eat breakfast on weekdays.","usually; hardly"),
        ],
        "reading_title": "Teen Health Report",
        "reading_text": [
            "We did a survey on teen health habits. Here are the results.",
            "Only 25% of teens exercise every day. Most teens exercise once or twice a week. 45% of teens spend more than two hours on screens every day.",
            "Teens who exercise more sleep better and feel happier. Experts say teens should exercise at least three times a week.",
            "Good habits start small. Try to walk for 20 minutes every day. Your body and mind will thank you!",
        ],
        "reading_gloss": [("survey","n. 调查"),("expert","n. 专家"),("screen","n. 屏幕"),("at least","至少")],
        "reading_qs": [
            ("阅读","★★☆","1. What percent of teens exercise every day?","25%"),
            ("阅读","★★☆","2. How much screen time do 45% of teens have?","More than two hours a day."),
            ("阅读","★★★","3. What advice do experts give?","Exercise at least three times a week and walk 20 minutes daily."),
        ],
        "exam_q_type": "语法填空", "exam_q": "用所给词的适当形式填空。",
        "exam_passage": [
            "My aunt is a doctor. She works very hard. She (1)____ (usual) gets up at 6 a.m. and goes running. She (2)____ (exercise) for 30 minutes every morning. She (3)____ (hard) ever stays up late. She says good habits help her (4)____ (stay) healthy. I think I (5)____ (should) learn from her.",
        ],
        "exam_options": [],
        "exam_answers": ["(1) usually","(2) exercises","(3) hardly","(4) stay","(5) should"],
        "writing_prompt": '请写一份"My Healthy Habit Report"，描述你一周的健康习惯，至少用到 4 个频率副词。',
        "writing_framework": ["开头：引出话题——我的一周习惯。","主体：分饮食、运动、睡眠三方面描述。","结尾：总结哪些习惯好，哪些需要改进。"],
        "writing_model_en": "Let me report my healthy habits. I always get up at 6:30 and go to bed before 10 p.m. I usually eat three meals a day. I often eat fruit and vegetables. I exercise three times a week. But I hardly ever drink milk. I'm going to drink milk every day from now on.",
        "writing_model_cn": "我来汇报一下我的健康习惯。我总是 6:30 起床，晚上 10 点前睡觉。我通常一日三餐。我经常吃水果蔬菜，每周锻炼三次。但我几乎不喝牛奶。我打算从今以后每天喝牛奶。",
        "project_title": "Class Habit Survey",
        "project_desc": "在班里做一个小调查，收集 5 位同学的运动、阅读和屏幕时间数据，用英语写一份调查报告。",
        "project_steps": ["设计 3 个频率问题（运动/阅读/屏幕时间）。","采访 5 位同学，记录数据。","计算百分比并写报告。","在班里展示调查结果。"],
        "project_rubric": ["问题设计合理","数据准确完整","报告使用了频率副词和百分比表达","展示清晰"],
        "checklist": ["我能用 How often 提问","我能用频率副词描述习惯","我能用次数表达（once/twice/three times）","我能写一篇健康习惯报告"],
        "feynman": "假装你是健康杂志的记者，用英语采访一个同学的生活习惯。练习 How often 问句和频率副词。",
        "review": ["默写频率副词排序（always→never）","用 How often 写 3 个问句","写 5 句关于自己习惯的句子","复习 once/twice/three times 用法"],
        "next_unit_title": "I'm more outgoing than my sister.",
        "next_unit_desc": "下一单元你将学习形容词比较级，学会用 than 比较人和事物的不同。",
    },

    "u03": {
        "num": "U3", "title": "I'm more outgoing than my sister.", "topic": "个人特质",
        "en_topic": "Personal Traits & Comparisons",
        "functions": "Compare people using comparative adjectives",
        "grammar": "形容词比较级（-er / more）· than · as…as 同级比较",
        "writing": "My Best Friend and I",
        "can_do": ["能用 -er 和 more 构成比较级","能用 than 比较两个人","能用 as…as 表示同级比较","能写一篇比较自己和朋友的短文"],
        "dialogue_scene": "班会课上，同学们讨论自己和家人的性格差异。",
        "dialogue": [
            ("Anna","Mom, am I more like you or Dad?","妈妈，我更像你还是爸爸？"),
            ("Mom","You look like your father, but you're more outgoing than him.","你长得像你爸爸，但性格比他外向。"),
            ("Anna","Really? Dad seems pretty outgoing too.","是吗？爸爸看起来也挺外向的。"),
            ("Mom","Well, your dad is funnier than me. But I'm more serious than him.","嗯，你爸爸比我幽默。但我比他认真。"),
            ("Anna","What about my sister?","那姐姐呢？"),
            ("Mom","She's quieter than you. But she's more hard-working. You two are very different.","她比你安静，但她更勤奋。你俩很不一样。"),
            ("Anna","I think we're both smart and kind. That's what matters!","我觉得我俩都聪明善良，这才是重要的！"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>You're more outgoing than him.</em> → 多音节形容词比较级：<strong>more + adj. + than</strong>",
            "<strong>2.</strong> <em>Your dad is funnier than me.</em> → 辅音+y 结尾改 y 为 i + er：<strong>funny → funnier</strong>",
            "<strong>3.</strong> <em>She's quieter than you.</em> → <strong>quiet → quieter</strong>（双音节以 e 结尾 +r）",
            "<strong>4.</strong> <em>We're both smart and kind.</em> → <strong>both</strong> 意为\"两者都\"，放在 be 动词后、实义动词前。",
        ],
        "vocab": [
            ("outgoing","ˌaʊtˈɡoʊɪŋ","adj.","外向的","She is more outgoing than her brother.","她比她弟弟外向。"),
            ("serious","ˈsɪriəs","adj.","严肃的；认真的","He is a serious student.","他是个认真的学生。"),
            ("hard-working","hɑːrd ˈwɜːrkɪŋ","adj.","勤奋的","My sister is very hard-working.","我姐姐非常勤奋。"),
            ("quiet","ˈkwaɪət","adj.","安静的；文静的","Lisa is quieter than her twin sister.","Lisa 比她的双胞胎妹妹安静。"),
            ("funny","ˈfʌni","adj.","有趣的；好笑的","He tells funny stories.","他讲很有趣的故事。"),
            ("smart","smɑːrt","adj.","聪明的；机灵的","Dogs are smart animals.","狗是聪明的动物。"),
            ("kind","kaɪnd","adj.","善良的；友好的","A kind person always helps others.","善良的人总是帮助别人。"),
            ("lazy","ˈleɪzi","adj.","懒惰的","Don't be lazy. Do your homework now.","别偷懒，现在做作业。"),
            ("though","ðoʊ","conj.","虽然；尽管","He's quiet, though he has many friends.","他虽然安静，但朋友很多。"),
            ("both","boʊθ","adj./pron.","两者都","Both of my parents are teachers.","我父母都是老师。"),
            ("better","ˈbetər","adj.","更好的(well 的比较级)","I am getting better at English.","我的英语在进步。"),
            ("win","wɪn","v.","赢；获胜","I hope our team can win.","我希望我们队能赢。"),
        ],
        "patterns": [
            ("形容词比较级 + than", "比较两个人/物", "<span class=\"slot\">She is taller</span> than <span class=\"slot\">me</span>."),
            ("more + 多音节形容词 + than", "多音节词比较级", "She is <span class=\"slot\">more outgoing</span> than <span class=\"slot\">her sister</span>."),
            ("as + 原级 + as", "同级比较", "He is <span class=\"slot\">as tall as</span> <span class=\"slot\">his father</span>."),
        ],
        "grammar_title": "形容词比较级",
        "grammar_sections": [
            ("比较级构成规则", [
                ("规则","构成方法","示例"),
                ("单音节/部分双音节","+er","tall → taller; short → shorter"),
                ("以 e 结尾","+r","large → larger; nice → nicer"),
                ("辅音+y 结尾","变 y 为 i +er","funny → funnier; easy → easier"),
                ("重读闭音节","双写尾字母 +er","big → bigger; hot → hotter"),
                ("多音节/部分双音节","more + 原级","outgoing → more outgoing; beautiful → more beautiful"),
            ]),
            ("不规则比较级", [
                ("原级","比较级","中文"),
                ("good/well","better","更好的"),
                ("bad/badly","worse","更差的"),
                ("many/much","more","更多的"),
                ("little","less","更少的"),
                ("far","farther/further","更远的"),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="She is more taller than me.">She is more taller than me.</span>（taller 已是比较级，不加 more）',
            '✅ <span class="correct" data-speak="She is taller than me.">She is taller than me.</span>',
            '❌ <span class="wrong" data-speak="He is more smart than his brother.">He is more smart than his brother.</span>（smart 单音节用 smarter）',
            '✅ <span class="correct" data-speak="He is smarter than his brother.">He is smarter than his brother.</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[比较级] Tom is ____ (tall) than his best friend.","taller"),
            ("基础","★☆☆","[比较级] She is ____ (outgoing) than me.","more outgoing"),
            ("基础","★☆☆","[选择] My sister is ____ (funny / funnier) than me.","funnier"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改错] He is more lazy than his brother.","He is lazier than his brother."),
            ("提升","★★☆","[同义句] I am not as tall as Jim. = Jim ____ ____ than me.","Jim is taller than me."),
            ("提升","★★☆","[填空] Who is ____ (good) at English, Tom or Jerry?","better"),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 这部电影比那部有趣得多。","This movie is much funnier than that one."),
            ("挑战","★★★","[补全] A: Who is more hard-working, you or your sister?<br>B: I think ____.","自由回答，如\"I think my sister is more hard-working than me.\""),
        ],
        "reading_title": "Twin Brothers, Different Personalities",
        "reading_text": [
            "Leo and Sam are twin brothers. They look the same, but they are very different.",
            "Leo is more outgoing. He loves to talk and make friends. He is also more athletic and plays basketball every day. Sam is quieter and more serious. He enjoys reading and drawing.",
            "Although they are different, they get on well. Leo helps Sam practice basketball, and Sam helps Leo with math.",
            "Leo says, \"Sam is smarter at school, but I'm better at sports. We learn from each other!\"",
        ],
        "reading_gloss": [("twin","n./adj. 双胞胎的"),("athletic","adj. 运动型的"),("although","conj. 虽然"),("get on well","相处融洽"),("learn from each other","互相学习")],
        "reading_qs": [
            ("阅读","★★☆","1. Who is more outgoing, Leo or Sam?","Leo."),
            ("阅读","★★☆","2. What does Sam enjoy doing?","Reading and drawing."),
            ("阅读","★★★","3. How do they help each other?","Leo helps Sam with basketball. Sam helps Leo with math."),
        ],
        "exam_q_type": "完形填空",
        "exam_q": "阅读短文，选择最佳选项。",
        "exam_passage": ["My best friend Lucy is different from me. She is (1)____ (outgoing) than me, and she is (2)____ (funny) than anyone I know. I am (3)____ (quiet) and more serious. But we have one thing (4)____ common—we are both kind. A good friend (5)____ like a mirror. You can see yourself in your friend."],
        "exam_options": [
            ("1.",{"A":"outgoing","B":"more outgoing","C":"most outgoing","D":"outgoinger"}),
            ("2.",{"A":"funny","B":"funnier","C":"funniest","D":"more funny"}),
            ("3.",{"A":"quiet","B":"quieter","C":"quietest","D":"more quiet"}),
            ("4.",{"A":"in","B":"on","C":"at","D":"for"}),
            ("5.",{"A":"is","B":"are","C":"be","D":"am"}),
        ],
        "exam_answers": ["1. B (more outgoing)","2. B (funnier)","3. B (quieter)","4. A (in)","5. A (is)"],
        "writing_prompt": '请以"My Best Friend and I"为题，从外貌、性格、爱好三方面比较你和你的好朋友。',
        "writing_framework": ["开头：介绍你的好朋友是谁。","主体：从三方面比较（外貌/性格/爱好）。","结尾：总结虽然不同，但友情深厚。"],
        "writing_model_en": "My best friend is Li Ming. He is taller than me, but I am heavier than him. He is more outgoing. He likes to talk and play with others. I am quieter and I enjoy reading. However, we both like sports. He is better at basketball, and I am better at running. We learn from each other. Good friends don't need to be the same!",
        "writing_model_cn": "我最好的朋友是李明。他比我高，但我比他重。他更外向，喜欢和别人聊天玩耍。我比较安静，喜欢阅读。不过我们都喜欢运动。他篮球更好，我跑步更好。我们互相学习。好朋友不需要一模一样！",
        "project_title": "Find the Differences",
        "project_desc": "找一位同学或家人做搭档，用英语比较你们之间的 5 个相同点和 5 个不同点。做成一个对比海报。",
        "project_steps": ["和搭档讨论各自的性格、爱好、外貌。","列出 5 个相同点（用 both 和 as…as）。","列出 5 个不同点（用比较级）。","做成对比海报并展示。"],
        "project_rubric": ["内容完整：5 same + 5 different","语法正确：比较级和同级比较","创意排版","展示流利度"],
        "checklist": ["我能用 -er 和 more 构成比较级","我能用 than 进行比较","我能用 as…as 表示同级","我能写比较自己和朋友的短文"],
        "feynman": "假装你是电视主持人，用英语比较两个明星的性格和外貌。练习比较级和 as…as。",
        "review": ["默写 10 个形容词的比较级","写出 5 个比较句（than）","写出 3 个同级比较句（as…as）","写一段比较你自己和家人的短文"],
        "next_unit_title": "What's the best movie theater?",
        "next_unit_desc": "下一单元你将学习形容词最高级，学会用 best / worst 等评价三个以上的人或物。",
    },

    "u04": {
        "num": "U4", "title": "What's the best movie theater?", "topic": "偏好比较",
        "en_topic": "Choosing the Best Place",
        "functions": "Make comparisons and give opinions using superlatives",
        "grammar": "形容词最高级（-est / most）· Which/Who is the…?",
        "writing": "A Review of My Favorite Place",
        "can_do": ["能用 -est 和 most 构成最高级","能用 Which/Who is the… 提问","能用最高级作评价和推荐","能写一篇场所评价短文"],
        "dialogue_scene": "几个同学在讨论学校附近哪家店最好。",
        "dialogue": [
            ("Tom","Let's go to the movies this weekend. Which theater is the best?","周末去看电影吧。哪家影院最好？"),
            ("Lisa","I think Sunshine Cinema is the best. It has the biggest screens.","我觉得 Sunshine 影院最好，屏幕最大。"),
            ("Tom","But it's also the most expensive. How about Town Cinema?","但也是最贵的。Town 影院呢？"),
            ("Lisa","Town Cinema is the cheapest, but it's the most uncomfortable.","Town 最便宜，但也是最不舒服的。"),
            ("Tom","What about Moonlight Theater? It's close to our school.","Moonlight 剧院呢？离学校近。"),
            ("Lisa","Moonlight is the most popular. The seats are the most comfortable, and the service is the friendliest.","Moonlight 最受欢迎，座位最舒服，服务最友好。"),
            ("Tom","OK, let's go to Moonlight then! Which movie is the most exciting?","那就去 Moonlight！哪部电影最刺激？"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>Which theater is the best?</em> → 最高级问句：<strong>Which/Who + be + the + 最高级?</strong>",
            "<strong>2.</strong> <em>It has the biggest screens.</em> → <strong>the + 最高级 + 名词</strong>：big → biggest, 重读闭音节双写 g + est",
            "<strong>3.</strong> <em>It's the most expensive.</em> → 多音节词最高级：<strong>the most + 原级</strong>",
            "<strong>4.</strong> <em>The service is the friendliest.</em> → 辅音+y 结尾：<strong>friendly → friendliest</strong>",
        ],
        "vocab": [
            ("theater","ˈθɪətər","n.","剧院；电影院","Which theater do you like best?","你最喜欢哪家影院？"),
            ("comfortable","ˈkʌmftəbl","adj.","舒适的","These seats are very comfortable.","这些座位很舒服。"),
            ("screen","skriːn","n.","屏幕","The screen is the biggest in town.","这是镇上最大的屏幕。"),
            ("service","ˈsɜːrvɪs","n.","服务","The service here is the best.","这里的服务最好。"),
            ("popular","ˈpɑːpjələr","adj.","受欢迎的","This is the most popular restaurant.","这是最受欢迎的餐厅。"),
            ("cheap","tʃiːp","adj.","便宜的","The tickets are the cheapest on Monday.","周一票最便宜。"),
            ("expensive","ɪkˈspensɪv","adj.","贵的","It's the most expensive theater.","这是最贵的影院。"),
            ("close","kloʊs","adj.","近的","The park is close to my home.","公园离我家很近。"),
            ("quality","ˈkwɑːləti","n.","质量","The food quality is the best here.","这里的食物质量最好。"),
            ("choose","tʃuːz","v.","选择","You can choose any seat you like.","你可以选任何你喜欢的座位。"),
        ],
        "patterns": [
            ("Which/Who + be + the + 最高级?", "最高级疑问句", "Which theater <span class=\"slot\">is the best</span>? / Who <span class=\"slot\">is the tallest</span> in your class?"),
            ("the + 最高级 + 名词", "最高级基本结构", "This is <span class=\"slot\">the biggest</span> screen. / It's <span class=\"slot\">the most popular</span> place."),
            ("One of the + 最高级 + 复数名词", "最高级短语", "It's <span class=\"slot\">one of the best</span> restaurants in town."),
        ],
        "grammar_title": "形容词最高级",
        "grammar_sections": [
            ("最高级构成规则", [
                ("规则","构成方法","示例"),
                ("单音节","the + adj. + est","tall → the tallest"),
                ("以 e 结尾","the + adj. + st","large → the largest"),
                ("辅音+y","the + 变 i + est","happy → the happiest"),
                ("重读闭音节","双写 + est","big → the biggest, hot → the hottest"),
                ("多音节","the most + adj.","expensive → the most expensive"),
                ("不规则","特殊变化","good → the best, bad → the worst"),
            ]),
            ("最高级常用句型", [
                ("句型","示例"),
                ("the + 最高级 + 范围","She is the tallest in our class."),
                ("one of the + 最高级 + 复数","It's one of the best movies I've seen."),
                ("the + 序数词 + 最高级","She is the second tallest girl."),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="She is most beautiful girl.">She is most beautiful girl.</span>（最高级前必须加 the）',
            '✅ <span class="correct" data-speak="She is the most beautiful girl.">She is the most beautiful girl.</span>',
            '❌ <span class="wrong" data-speak="This is the most cheapest.">This is the most cheapest.</span>（cheap 单音节不用 most）',
            '✅ <span class="correct" data-speak="This is the cheapest.">This is the cheapest.</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[最高级] Tom is the ____ (tall) boy in our class.","tallest"),
            ("基础","★☆☆","[最高级] This is the ____ (expensive) watch in the store.","most expensive"),
            ("基础","★☆☆","[不规则] She is the ____ (good) student in her class.","best"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改错] It's the most big theater in town.","It's the biggest theater in town."),
            ("提升","★★☆","[句型] This movie is the most interesting. (改为比较级)<br>→ This movie is ____ ____ than that one.","more interesting"),
            ("提升","★★☆","[填空] Spring is the ____ (good) season of the year.","best"),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 这是我们学校第二大的图书馆。","It's the second largest library in our school."),
            ("挑战","★★★","[补全] A: Which restaurant do you like best?<br>B: ____","自由回答，如 I like Happy Kitchen best because it has the most delicious food."),
        ],
        "reading_title": "The Best Places in My Town",
        "reading_text": [
            "I live in a small but nice town. There are many interesting places here.",
            "The best park is Central Park. It's the biggest and the cleanest. Many people go there on weekends. The best place for food is Mr. Wang's Noodle House. The noodles are the most delicious and the cheapest.",
            "The library is the quietest place. It's also the most popular place for students. I go there every weekend.",
            "What's the best place in your town?",
        ],
        "reading_gloss": [("central","adj. 中心的"),("noodle","n. 面条"),("delicious","adj. 美味的")],
        "reading_qs": [
            ("阅读","★★☆","1. Which park is the best in the town?","Central Park."),
            ("阅读","★★☆","2. Why is Mr. Wang's Noodle House the best for food?","The noodles are the most delicious and the cheapest."),
            ("阅读","★★★","3. Where do students like to go most?","The library."),
        ],
        "exam_q_type": "语法填空", "exam_q": "用括号内单词的适当形式填空。",
        "exam_passage": ["There are three cinemas in our city. Town Cinema is the (1)____ (old) one. City Theater has the (2)____ (comfortable) seats. But Moon Theater is the (3)____ (good) of all. It has the (4)____ (friendly) service and the (5)____ (big) screens. I think it's the (6)____ (popular) cinema here."],
        "exam_options": [],
        "exam_answers": ["(1) oldest","(2) most comfortable","(3) best","(4) friendliest","(5) biggest","(6) most popular"],
        "writing_prompt": '请写一篇短文"A Review of My Favorite Place"，用最高级介绍你最喜欢的一个场所（影院、餐厅、公园等）。',
        "writing_framework": ["开头：介绍最喜欢的场所是谁。","主体：用最高级从 3 个方面说明理由。","结尾：推荐大家去看看。"],
        "writing_model_en": "My favorite place is the Sunshine Library. It is the quietest place in my city. It has the most comfortable reading chairs and the friendliest workers. I can find the newest books there. It's also one of the cheapest places—I can read for free! If you like reading, you should visit it.",
        "writing_model_cn": "我最喜欢的地方是 Sunshine 图书馆。它是我城市里最安静的地方，有最舒适的阅读椅和最友好的工作人员。我可以找到最新的书。而且也是最便宜的地方之一——免费阅读！如果你喜欢看书，你应该去看看。",
        "project_title": "Best Place Guide",
        "project_desc": "小组合作制作一份\"最佳场所指南\"(Best Place Guide)，评价学校附近的最好的 3 个场所。",
        "project_steps": ["小组讨论学校附近有哪些场所。","每人选一个场所，用最高级写出评价。","汇总成一份指南，配上评分和推荐语。","在班里展示和投票。"],
        "project_rubric": ["每个场所从 3 个方面评价","正确使用最高级","有理有据，让人信服","展示有互动"],
        "checklist": ["我能用 the + 最高级 进行评价","我能用 Which is the… 提问","我能区分比较级和最高级","我能写场所评价短文"],
        "feynman": "假装你是美食评论家，用英语评价三家餐厅，用最高级说出哪家最好、为什么。",
        "review": ["默写 10 个形容词的最高级","写出 5 个最高级句子","改写 5 个句子从比较级到最高级","写一段推荐你最喜欢的电影"],
        "next_unit_title": "Do you want to watch a game show?",
        "next_unit_desc": "下一单元你将学习如何用不定式表达目的和喜好，谈论电视节目和电影。",
    },

    "u05": {
        "num": "U5", "title": "Do you want to watch a game show?", "topic": "媒体偏好",
        "en_topic": "TV Shows & Movies", "functions": "Express preferences and make plans",
        "grammar": "不定式作宾语（want/plan/hope to do）· 动词 + to do 结构",
        "writing": "My Favorite TV Show",
        "can_do": ["能用 want/plan/hope to do 表达计划","能用 would like to 礼貌表达意愿","能谈论电视节目类型和喜好","能写一篇节目推荐短文"],
        "dialogue_scene": "几个朋友在讨论今晚看什么电视节目。",
        "dialogue": [
            ("Jenny","What do you want to watch tonight?","今晚你想看什么？"),
            ("Mike","I plan to watch the game show. It's very exciting.","我打算看游戏类节目，特别刺激。"),
            ("Jenny","I don't like game shows. I hope to watch a sitcom. They make me laugh.","我不喜欢游戏节目。我希望看情景喜剧，能让我笑。"),
            ("Mike","But sitcoms are boring. How about a talk show?","但情景喜剧很无聊。脱口秀呢？"),
            ("Jenny","Talk shows are OK. But I would like to watch a talent show.","脱口秀还行，但我想看才艺秀。"),
            ("Mike","Good idea! I hope to see some great singers.","好主意！我希望能看到一些好歌手。"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>What do you want to watch?</em> → <strong>want to do</strong>：想要做某事。to 后跟动词原形。",
            "<strong>2.</strong> <em>I plan to watch the game show.</em> → <strong>plan to do</strong>：计划做某事。",
            "<strong>3.</strong> <em>I hope to watch a sitcom.</em> → <strong>hope to do</strong>：希望做某事。",
            "<strong>4.</strong> <em>I would like to watch a talent show.</em> → <strong>would like to do</strong>：想要（礼貌表达）。",
            "<strong>5.</strong> 电视节目类型：<strong>game show</strong> 游戏类 / <strong>sitcom</strong> 情景喜剧 / <strong>talk show</strong> 脱口秀 / <strong>talent show</strong> 才艺秀 / <strong>sports show</strong> 体育节目 / <strong>news</strong> 新闻",
        ],
        "vocab": [
            ("sitcom","ˈsɪtkɑːm","n.","情景喜剧","I like watching sitcoms.","我喜欢看情景喜剧。"),
            ("talent","ˈtælənt","n.","才能；天赋","She has a talent for singing.","她有唱歌天赋。"),
            ("plan","plæn","v.","计划","We plan to go hiking this weekend.","我们计划周末去远足。"),
            ("hope","hoʊp","v.","希望","I hope to visit Beijing one day.","我希望有一天去北京。"),
            ("educational","ˌedʒuˈkeɪʃənl","adj.","教育的；有教育意义的","Documentaries are educational.","纪录片很有教育意义。"),
            ("meaningless","ˈmiːnɪŋləs","adj.","毫无意义的","I think some ads are meaningless.","我觉得有些广告毫无意义。"),
            ("enjoyable","ɪnˈdʒɔɪəbl","adj.","令人愉快的","The movie was very enjoyable.","这部电影非常好看。"),
            ("expect","ɪkˈspekt","v.","期待；预料","I expect to learn a lot from this show.","我期待从这个节目中学到很多。"),
            ("famous","ˈfeɪməs","adj.","著名的","She wants to be a famous singer.","她想成为著名的歌手。"),
            ("appear","əˈpɪr","v.","出现；露面","Many stars appear on this show.","很多明星在这个节目中出现。"),
        ],
        "patterns": [
            ("want / plan / hope + to do", "表达意愿和计划", "I <span class=\"slot\">want to watch</span> a movie. / She <span class=\"slot\">plans to visit</span> her grandma."),
            ("would like + to do", "礼貌表达意愿", "I <span class=\"slot\">would like to go</span> shopping. / <span class=\"slot\">Would you like to</span> join us?"),
            ("expect / decide + to do", "其他接 to do 的动词", "I <span class=\"slot\">decided to learn</span> English. / I <span class=\"slot\">expect to finish</span> it today."),
        ],
        "grammar_title": "不定式作宾语（动词 + to do）",
        "grammar_sections": [
            ("常见后接 to do 的动词", [
                ("动词","含义","示例"),
                ("want","想要","I want to be a teacher."),
                ("plan","计划","We plan to have a party."),
                ("hope","希望","I hope to see you soon."),
                ("would like","想要","I would like to drink coffee."),
                ("decide","决定","She decided to join the club."),
                ("expect","期待","I expect to pass the exam."),
                ("learn","学习","He is learning to swim."),
            ]),
            ("否定形式", [
                ("结构","示例"),
                ("动词 + not + to do","I decided <strong>not</strong> to go."),
                ("would like + not + to do","I would like <strong>not</strong> to be late."),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="I want watch TV.">I want watch TV.</span>（动词 want 后需加 to）',
            '✅ <span class="correct" data-speak="I want to watch TV.">I want to watch TV.</span>',
            '❌ <span class="wrong" data-speak="He doesn\'t want to eats.">He doesn\'t want to eats.</span>（to 后动词用原形）',
            '✅ <span class="correct" data-speak="He doesn\'t want to eat.">He doesn\'t want to eat.</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[want] I ____ ____ watch a movie tonight.","want to"),
            ("基础","★☆☆","[plan] She ____ ____ study abroad next year.","plans to"),
            ("基础","★☆☆","[选择] I would like ____ (go / to go) shopping this weekend.","to go"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改错] He hopes watch the game show tonight.","He hopes to watch the game show tonight."),
            ("提升","★★☆","[句型] I want to watch TV. (改为否定句)","I don't want to watch TV."),
            ("提升","★★☆","[填空] They decided ____ (not / go) to the party.","not to go"),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 你今晚打算做什么？——我计划在家看一部有趣的电影。","What are you going to do tonight? — I plan to watch an interesting movie at home."),
            ("挑战","★★★","[补全] A: Do you want to watch a talent show?<br>B: ____, I ____ ____ watch a sports show.","No, I would like to watch a sports show."),
        ],
        "reading_title": "TV Habits of Chinese Teens",
        "reading_text": [
            "What do Chinese teenagers like to watch on TV? A survey gives us the answer.",
            "Game shows are the most popular. About 35% of teens choose to watch them. Next are talent shows. Many teens hope to see amazing performances.",
            "Sitcoms are also popular. Teens want to relax and laugh after a long day at school. Talk shows are less popular, but some teens find them educational.",
            "Interestingly, many teens also choose to watch the news. They want to know what is happening around the world.",
        ],
        "reading_gloss": [("teenager","n. 青少年"),("amazing","adj. 令人惊叹的"),("performance","n. 表演"),("interestingly","adv. 有趣的是")],
        "reading_qs": [
            ("阅读","★★☆","1. What is the most popular TV show among teens?","Game shows."),
            ("阅读","★★☆","2. Why do teens watch sitcoms?","To relax and laugh."),
            ("阅读","★★★","3. Why do some teens watch the news?","To know what is happening around the world."),
        ],
        "exam_q_type": "完形填空",
        "exam_q": "阅读短文，选择最佳选项。",
        "exam_passage": ["I (1)____ to be a TV reporter one day. That's why I like to watch different TV shows. I (2)____ to learn from them. I love news because it's educational. I also like game shows because they are exciting. I don't (3)____ to watch sitcoms. I think they are (4)____. Do you want (5)____ watch TV with me this weekend?"],
        "exam_options": [
            ("1.",{"A":"want","B":"wants","C":"wanted","D":"wanting"}),
            ("2.",{"A":"hope","B":"hopes","C":"hoping","D":"to hope"}),
            ("3.",{"A":"likes","B":"like","C":"liked","D":"liking"}),
            ("4.",{"A":"educational","B":"enjoyable","C":"meaningless","D":"exciting"}),
            ("5.",{"A":"at","B":"in","C":"to","D":"for"}),
        ],
        "exam_answers": ["1. A (want)","2. A (hope)","3. B (like)","4. C (meaningless)","5. C (to)"],
        "writing_prompt": '请以"My Favorite TV Show"为题，写 60-80 词介绍你最喜欢的电视节目，说明喜欢的原因。',
        "writing_framework": ["开头：我最喜欢的节目是什么。","主体：节目内容+喜欢理由（用到 want/hope/enjoy）。","结尾：推荐大家去看。"],
        "writing_model_en": "My favorite TV show is \"China's Got Talent\". I want to watch it every week. The performers are amazing. Some singers make me want to cry, and some dancers make me laugh. I hope to learn from them. This show also teaches me to follow my dreams. I think everyone should watch it!",
        "writing_model_cn": "我最喜欢的节目是《中国达人秀》。我每周都想看。表演者很精彩。有些歌手让我感动，有些舞者让我开心。我希望向他们学习。这个节目也教会我追梦。我觉得每个人都应该看看！",
        "project_title": "Our Class TV Guide",
        "project_desc": "在班里做一个小调查，统计大家最喜欢的电视节目类型，制作一份\"班级电视指南\"(Class TV Guide)。",
        "project_steps": ["设计调查问卷（列出 6 种节目类型）。","采访至少 10 位同学。","统计结果，画出图表。","用英语写出调查报告并展示。"],
        "project_rubric": ["问卷设计合理","数据真实完整","报告中用到了 want/hope/plan to do","图表清晰"],
        "checklist": ["我能用 want/plan/hope to do 表达意愿","我能用 would like to 礼貌表达","我能区分不同的电视节目类型","我能写节目推荐短文"],
        "feynman": "假装你是电视台的节目策划人，用英语向同学推荐一档新节目。练习 want/hope/plan to do。",
        "review": ["默写 8 个接 to do 的动词","用 want/plan/hope 各写 2 个句子","写一段节目评价","复习 would like to 礼貌用法"],
        "next_unit_title": "I'm going to study computer science.",
        "next_unit_desc": "下一单元你将学习谈论未来职业规划，用 be going to 表达志向和梦想。",
    },

    "u06": {
        "num": "U6", "title": "I'm going to study computer science.", "topic": "职业规划",
        "en_topic": "Future Plans & Dream Jobs", "functions": "Talk about future plans and dream jobs",
        "grammar": "be going to 表示未来计划 · what/where/how 引导特殊疑问句",
        "writing": "My Dream Job",
        "can_do": ["能用 be going to 谈论未来职业规划","能询问和回答职业相关的 wh- 问题","能描述实现梦想需要做的准备","能写一篇职业规划短文"],
        "dialogue_scene": "班会上，同学们在分享自己的职业梦想和实现计划。",
        "dialogue": [
            ("Teacher","What do you want to be when you grow up?","你们长大了想做什么？"),
            ("Wang Lin","I'm going to be a computer programmer. I'm going to study computer science.","我想当程序员，准备学计算机科学。"),
            ("Teacher","That sounds cool! What about you, Li Mei?","听起来很酷！你呢，李梅？"),
            ("Li Mei","I'm going to be a doctor. I'm going to study medicine at a famous university.","我想当医生，准备上一所名牌大学学医。"),
            ("Teacher","Zhang Wei, what are you going to be?","张伟，你打算做什么？"),
            ("Zhang Wei","I'm not sure yet. Maybe I'm going to be a teacher like you.","还不确定。也许当老师，像您一样。"),
            ("Teacher","That's great! How are you going to do that?","很好！你打算怎么做？"),
            ("Zhang Wei","I'm going to study hard and learn teaching skills.","我打算努力学习并学习教学技能。"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>What do you want to be when you grow up?</em> → <strong>want to be</strong> \"想成为\" + 职业名词。<strong>when you grow up</strong> \"当你长大\"。",
            "<strong>2.</strong> <em>I'm going to be a computer programmer.</em> → <strong>be going to be + 职业</strong> 表示想成为什么。",
            "<strong>3.</strong> <em>How are you going to do that?</em> → 用 <strong>How</strong> 问方法：How + be + 主语 + going to + 动词?",
            "<strong>4.</strong> <em>I'm going to study computer science.</em> → 接具体行动：<strong>be going to + 动词原形</strong>。",
        ],
        "vocab": [
            ("programmer","ˈproʊɡræmər","n.","程序员","My uncle is a computer programmer.","我叔叔是程序员。"),
            ("science","ˈsaɪəns","n.","科学；理科","Computer science is very useful.","计算机科学很有用。"),
            ("medicine","ˈmedɪsn","n.","医学；药","She wants to study medicine in college.","她想在大学学医。"),
            ("university","ˌjuːnɪˈvɜːrsəti","n.","大学","Which university do you want to go to?","你想上哪所大学？"),
            ("engineer","ˌendʒɪˈnɪr","n.","工程师","He's going to be an engineer.","他打算当工程师。"),
            ("pilot","ˈpaɪlət","n.","飞行员","It's my dream to be a pilot.","当飞行员是我的梦想。"),
            ("cook","kʊk","n.","厨师","She is a great cook.","她是个好厨师。"),
            ("violinist","ˌvaɪəˈlɪnɪst","n.","小提琴手","The violinist plays beautifully.","这位小提琴手演奏得很美。"),
            ("college","ˈkɑːlɪdʒ","n.","学院；大学","I'm going to go to college after high school.","高中毕业后我要上大学。"),
            ("education","ˌedʒuˈkeɪʃn","n.","教育","Education is important for everyone.","教育对每个人都很重要。"),
            ("artist","ˈɑːrtɪst","n.","艺术家","She wants to become an artist.","她想成为艺术家。"),
            ("resolution","ˌrezəˈluːʃn","n.","决心；决定","I made a New Year's resolution to study harder.","我下了新年决心要更努力学习。"),
        ],
        "patterns": [
            ("be going to be + 职业", "表达未来职业", "I <span class=\"slot\">am going to be</span> <span class=\"slot\">a doctor</span>."),
            ("How + be + going to + do?", "询问实现方法", "<strong>How</strong> <span class=\"slot\">are you going to</span> become a singer?"),
            ("What do you want to be?", "询问职业梦想", "<strong>What</strong> do you <span class=\"slot\">want to be</span> when you grow up?"),
        ],
        "grammar_title": "be going to 表示未来计划",
        "grammar_sections": [
            ("be going to 表计划", [
                ("人称","肯定句","否定句","疑问句"),
                ("I","I'm going to + v.","I'm not going to + v.","Am I going to + v.?"),
                ("He/She/It","He's going to + v.","He isn't going to + v.","Is he going to + v.?"),
                ("We/You/They","They're going to + v.","They aren't going to + v.","Are they going to + v.?"),
            ]),
            ("Wh- 疑问句", [
                ("问词","含义","示例"),
                ("What","什么","What are you going to do?"),
                ("Where","哪里","Where are you going to study?"),
                ("When","何时","When are you going to start?"),
                ("How","怎样","How are you going to do it?"),
                ("Who","谁","Who is going to help you?"),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="I going to be a doctor.">I going to be a doctor.</span>（遗漏 be 动词 am）',
            '✅ <span class="correct" data-speak="I am going to be a doctor.">I am going to be a doctor.</span>',
            '❌ <span class="wrong" data-speak="What you are going to do?">What you are going to do?</span>（疑问句语序错误）',
            '✅ <span class="correct" data-speak="What are you going to do?">What are you going to do?</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[be going to] I ____ ____ ____ be a pilot when I grow up.","am going to"),
            ("基础","★☆☆","[选择] What ____ she going to be? (is / are / am)","is"),
            ("基础","★☆☆","[职业] A person who writes computer programs is a ____.","programmer"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改错] He are going to study medicine.","He is going to study medicine."),
            ("提升","★★☆","[问答] Q: ____ ____ you going to be? A: I'm going to be a teacher.","What are"),
            ("提升","★★☆","[否定] I'm going to give up. (改为否定句)","I'm not going to give up."),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 你打算怎样实现你的梦想？","How are you going to make your dream come true?"),
            ("挑战","★★★","[补全] A: ____ ____ you going to study?<br>B: I'm going to study at Peking University.","Where are"),
        ],
        "reading_title": "Dreams and Actions",
        "reading_text": [
            "Everyone has a dream. But how can we make our dreams come true?",
            "First, find out what you are good at. If you love drawing, maybe you are going to be an artist. If you enjoy helping others, maybe you are going to be a doctor.",
            "Second, make a plan. What are you going to do this year? What subjects are you going to study hard?",
            "Third, take action. A dream without action is just a wish. Start today!",
        ],
        "reading_gloss": [("come true","实现"),("take action","采取行动"),("without","prep. 没有")],
        "reading_qs": [
            ("阅读","★★☆","1. What is the first step to make dreams come true?","Find out what you are good at."),
            ("阅读","★★☆","2. What is the second step?","Make a plan."),
            ("阅读","★★★","3. What does \"A dream without action is just a wish\" mean?","只有梦想没有行动，那只是空想。"),
        ],
        "exam_q_type": "语法填空", "exam_q": "用括号内单词的适当形式填空。",
        "exam_passage": ["My brother (1)____ (be) going to be a pilot. He (2)____ (study) hard to get into a good university. He (3)____ (practice) his English every day because pilots need good English. I (4)____ (be) going to be a scientist. We (5)____ (have) big dreams! What are you going to (6)____ (be)?"],
        "exam_options": [],
        "exam_answers": ["(1) is","(2) studies","(3) practices","(4) am","(5) have","(6) be"],
        "writing_prompt": '请以"My Dream Job"为题，写 60-80 词短文，说说你梦想的职业和你打算如何实现它。',
        "writing_framework": ["开头：我梦想的职业是什么。","主体：为什么选择这个职业+我打算怎么做。","结尾：表达信心和期待。"],
        "writing_model_en": "When I grow up, I'm going to be a doctor. I want to help sick people. I'm going to study science and biology hard. I'm going to go to a good medical university. I know becoming a doctor is not easy, but I'm not going to give up. I'm going to work hard every day to make my dream come true.",
        "writing_model_cn": "等我长大了，我打算当一名医生。我想帮助病人。我打算学好科学和生物。我打算上一所好的医科大学。我知道当医生不容易，但我不会放弃。我打算每天努力，实现梦想。",
        "project_title": "Career Day Presentation",
        "project_desc": "选择一个你感兴趣的职业，做 2 分钟英语展示，介绍这个职业的特点和你打算如何进入这个行业。",
        "project_steps": ["选择一个职业进行调研。","写出该职业的 3 个特点。","用 be going to 写出你的规划。","做成展示卡片并演讲。"],
        "project_rubric": ["信息准确","使用了 be going to","规划合理可行","表达流利自信"],
        "checklist": ["我能用 be going to 谈论职业规划","我能用 wh- 提问职业相关话题","我能描述实现梦想的步骤","我能写职业规划短文"],
        "feynman": "假装你在参加职业日(Career Day)，用英语向同学介绍你梦想的职业和实现计划。",
        "review": ["用 be going to 写 5 个未来计划","列出 10 种职业的英文","写出实现梦想的 3 个步骤","复习 wh- + be going to 疑问句"],
        "next_unit_title": "Will people have robots?",
        "next_unit_desc": "下一单元你将学习用 will 预测未来，讨论未来的科技和生活变化。",
    },

    "u07": {
        "num": "U7", "title": "Will people have robots?", "topic": "未来预测",
        "en_topic": "Future Life & Predictions", "functions": "Make predictions about the future",
        "grammar": "will 将来时 · there will be · 一般将来时的各种句式",
        "writing": "Life in 20 Years",
        "can_do": ["能用 will 预测未来","能用 there will be 描述存在","能区分 will 和 be going to","能写一篇未来生活预测短文"],
        "dialogue_scene": "科技课上，同学们在讨论 50 年后世界会是什么样子。",
        "dialogue": [
            ("Mr. Chen","Will people have robots in their homes in 50 years?","50 年后人们家里会有机器人吗？"),
            ("Liu Wei","Yes, I think every family will have a robot. Robots will do housework.","我觉得每个家庭都会有机器人。机器人会做家务。"),
            ("Lin Tao","Will kids still go to school?","孩子们还会去上学吗？"),
            ("Liu Wei","Maybe not. They will study at home on computers.","也许不会了。他们会在家通过电脑学习。"),
            ("Anna","I think there will be more trees and less pollution.","我觉得会有更多树，更少污染。"),
            ("Mr. Chen","That sounds great! Will there be flying cars?","听起来不错！会有飞行汽车吗？"),
            ("Anna","Yes, I think there will be. People will travel faster.","我觉得会有。人们出行会更快。"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>Will people have robots?</em> → <strong>will + 动词原形</strong> 表示未来预测。<strong>Will + 主语 + 动词?</strong> 一般疑问句。",
            "<strong>2.</strong> <em>There will be more trees.</em> → <strong>There will be + 名词</strong> \"将有……\"，be 不随后面名词变化。",
            "<strong>3.</strong> <em>Kids will study at home on computers.</em> → will 肯定句：<strong>主语 + will + 动词原形</strong>。",
            "<strong>4.</strong> <em>People will travel faster.</em> → will 后接比较级，表示未来会更快。",
        ],
        "vocab": [
            ("robot","ˈroʊbɑːt","n.","机器人","Robots will help us do housework.","机器人会帮我们做家务。"),
            ("pollution","pəˈluːʃn","n.","污染","There will be less pollution in the future.","未来污染会更少。"),
            ("environment","ɪnˈvaɪrənmənt","n.","环境","We should protect the environment.","我们应该保护环境。"),
            ("planet","ˈplænɪt","n.","行星；星球","Earth is our home planet.","地球是我们的家园。"),
            ("peace","piːs","n.","和平","I hope there will be world peace.","我希望世界和平。"),
            ("prediction","prɪˈdɪkʃn","n.","预测","Do you have a prediction about the future?","你对未来有预测吗？"),
            ("believe","bɪˈliːv","v.","相信","I believe there will be great changes.","我相信会有巨大的变化。"),
            ("future","ˈfjuːtʃər","n.","未来","The future is in our hands.","未来掌握在我们手中。"),
            ("danger","ˈdeɪndʒər","n.","危险","Some animals are in danger.","一些动物处于危险中。"),
            ("possible","ˈpɑːsəbl","adj.","可能的","Everything is possible.","一切皆有可能。"),
        ],
        "patterns": [
            ("will + 动词原形", "未来预测", "People <span class=\"slot\">will have</span> robots. / I <span class=\"slot\">will be</span> a doctor."),
            ("Will + 主语 + 动词?", "一般疑问句未来时", "<strong>Will</strong> <span class=\"slot\">there be</span> flying cars? / <strong>Will</strong> <span class=\"slot\">kids go</span> to school?"),
            ("There will be + 名词", "描述未来的存在", "There will be <span class=\"slot\">more trees</span>. / There will be <span class=\"slot\">less pollution</span>."),
        ],
        "grammar_title": "will 将来时",
        "grammar_sections": [
            ("will 句式总结", [
                ("句式","结构","示例"),
                ("肯定句","主语 + will + 动词","I will travel to the moon."),
                ("否定句","主语 + won't + 动词","People won't need cars."),
                ("一般疑问句","Will + 主语 + 动词?","Will everyone have a robot?"),
                ("特殊疑问句","Wh- + will + 主语 + 动词?","Where will people live?"),
            ]),
            ("there will be", [
                ("句式","示例"),
                ("肯定","There will be more people."),
                ("否定","There won't be any wars."),
                ("疑问","Will there be flying cars?"),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="People will has robots.">People will has robots.</span>（will 后动词用原形）',
            '✅ <span class="correct" data-speak="People will have robots.">People will have robots.</span>',
            '❌ <span class="wrong" data-speak="There will have more trees.">There will have more trees.</span>（固定搭配 there will be）',
            '✅ <span class="correct" data-speak="There will be more trees.">There will be more trees.</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[will] I think people ____ (will / are) live on the moon one day.","will"),
            ("基础","★☆☆","[否定] People ____ won\'t / don\'t) need to drive cars in the future.","won't"),
            ("基础","★☆☆","[there be] ____ ____ ____ more robots in 50 years? (Will there be)","Will there be"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改错] There will have less pollution.","There will be less pollution."),
            ("提升","★★☆","[问答] ____ will people live in the future? — On other planets.","Where"),
            ("提升","★★☆","[句型] Kids will go to school. (改为否定句)","Kids won't go to school."),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 50 年后人们将活到 200 岁吗？","Will people live to be 200 years old in 50 years?"),
            ("挑战","★★★","[补全] A: What will schools be like in the future?<br>B: ____","自由回答，如 There will be no heavy schoolbags. Students will use tablets."),
        ],
        "reading_title": "Life in 2124",
        "reading_text": [
            "What will life be like in 100 years? Let's make some predictions!",
            "First, there will be huge changes in transportation. Flying cars will take people anywhere they want. There won't be traffic jams anymore.",
            "Second, robots will do most of the housework. People will have more free time to relax and enjoy life.",
            "Third, there will be great schools. Students will learn through VR (virtual reality). They will visit ancient Rome or the deep ocean without leaving their rooms!",
            "The future is full of possibilities. What's your prediction?",
        ],
        "reading_gloss": [("huge","adj. 巨大的"),("transportation","n. 交通"),("traffic jam","交通堵塞"),("VR","虚拟现实"),("ancient","adj. 古老的"),("possibility","n. 可能性")],
        "reading_qs": [
            ("阅读","★★☆","1. How will people travel in the future?","By flying cars."),
            ("阅读","★★☆","2. Why will people have more free time?","Because robots will do most of the housework."),
            ("阅读","★★★","3. How will students learn in future schools?","Through VR—they can visit ancient Rome or the deep ocean."),
        ],
        "exam_q_type": "完形填空",
        "exam_q": "阅读短文，选择最佳选项。",
        "exam_passage": ["What (1)____ life be like in 50 years? I think there (2)____ be great changes. People (3)____ live longer. Many people (4)____ work from home. Robots will (5)____ us with housework. But there (6)____ be some problems too. What will you do to make the future better?"],
        "exam_options": [
            ("1.",{"A":"will","B":"is","C":"are","D":"was"}),
            ("2.",{"A":"is","B":"are","C":"will","D":"was"}),
            ("3.",{"A":"is","B":"are","C":"will","D":"won't"}),
            ("4.",{"A":"will","B":"are","C":"is","D":"be"}),
            ("5.",{"A":"help","B":"helping","C":"helped","D":"helps"}),
            ("6.",{"A":"will","B":"won't","C":"is","D":"are"}),
        ],
        "exam_answers": ["1. A (will)","2. C (will)","3. C (will)","4. A (will)","5. A (help)","6. A (will)"],
        "writing_prompt": '请以"Life in 20 Years"为题，写 60-80 词短文预测 20 年后你的生活（工作、家庭、科技方面）。',
        "writing_framework": ["开头：20 年后的总体预测。","主体：工作+家庭+科技三方面。","结尾：表达对未来的期待。"],
        "writing_model_en": "What will my life be like in 20 years? I think I will be a doctor. I will work in a big hospital. There will be smart robots to help me. I will live in a clean and green city. There will be no pollution. I will have a happy family. I will travel to space with my family on vacation. I'm looking forward to the future!",
        "writing_model_cn": "20 年后我的生活会是什么样？我想我会是一名医生，在一家大医院工作。会有智能机器人帮我。我会住在一个干净绿色的城市，没有污染。我会有一个幸福的家庭。我会和家人去太空度假。我期待未来！",
        "project_title": "Future Predictions Debate",
        "project_desc": "小组辩论：未来 50 年哪些预测会成真？每组选 3 个预测，用 will / won't 表达观点，并给出理由。",
        "project_steps": ["每个成员提出 2 个未来预测。","小组讨论，选出 3 个最可能和 3 个最不可能的。","准备辩论说辞。","进行班级辩论。"],
        "project_rubric": ["预测有创意","理由充分有逻辑","正确使用 will/won't","团队合作好"],
        "checklist": ["我能用 will 预测未来","我能用 there will be","我能区分 will 和 be going to","我能写未来预测短文"],
        "feynman": "假装你是一位未来学家，用英语对 100 年后的世界做 3 个预测。练习 will 和 there will be。",
        "review": ["用 will 写 5 个预测句子","用 there will be 写 3 个句子","比较 will 和 be going to 的区别","写一段 50 年后学校生活预测"],
        "next_unit_title": "Let's Communicate!",
        "next_unit_desc": "下一单元你将学习祈使句和提建议的表达方式，学会用英语有效沟通。",
    },

    "u08": {
        "num": "U8", "title": "Let's Communicate!", "topic": "沟通表达",
        "en_topic": "Effective Communication", "functions": "Give suggestions and respond politely",
        "grammar": "祈使句（肯定/否定）· Let's… · How about…? · 礼貌请求和回应",
        "writing": "A Persuasive Letter",
        "can_do": ["能用祈使句发出指令","能用 Let's 提建议","能用 How about/What about 给出方案","能用英语礼貌地请求和回应"],
        "dialogue_scene": "班长组织同学讨论班级存在问题并提出改进建议。",
        "dialogue": [
            ("Monitor","Class, let's talk about our problems. First, some students talk in class. Let's make some rules.","同学们，我们来讨论问题。首先有同学上课说话。我们定些规则吧。"),
            ("Li Ming","Don't talk when the teacher is speaking. It's not polite.","老师说话时不要讲话，这不礼貌。"),
            ("Wang Fang","How about having a \"quiet signal\"? When the teacher raises her hand, everyone stops talking.","来个\"安静信号\"怎么样？老师一抬手，所有人停止说话。"),
            ("Monitor","Great idea! Let's try it. Next, homework. Some students don't hand it in on time.","好主意！试试看。下一个问题，作业。有些同学不按时交。"),
            ("Zhang Lei","Let's set up a homework reminder group. We can help each other.","建个作业提醒群吧。我们可以互相帮助。"),
            ("Monitor","OK, let's do that. Let's work together to make our class better!","好的，就这么办。我们一起努力让班级更好！"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>Let's make some rules.</em> → <strong>Let's + 动词原形</strong> \"让我们做……\"，表建议。",
            "<strong>2.</strong> <em>Don't talk when the teacher is speaking.</em> → <strong>Don't + 动词原形</strong> \"不要做……\"，否定祈使句。",
            "<strong>3.</strong> <em>How about having a \"quiet signal\"?</em> → <strong>How about / What about + doing</strong> \"……怎么样？\" 提建议。",
            "<strong>4.</strong> <em>Let's set up a homework reminder group.</em> → <strong>set up</strong> 建立，<strong>reminder</strong> 提醒物。",
        ],
        "vocab": [
            ("communicate","kəˈmjuːnɪkeɪt","v.","交流；沟通","We should communicate with our parents.","我们应该和父母沟通。"),
            ("suggestion","səˈdʒestʃən","n.","建议","Do you have any suggestions?","你有什么建议吗？"),
            ("polite","pəˈlaɪt","adj.","礼貌的","It's polite to say \"thank you\".","说\"谢谢\"是礼貌的。"),
            ("signal","ˈsɪɡnəl","n.","信号；暗号","Let's agree on a signal.","我们来约定一个信号。"),
            ("remind","rɪˈmaɪnd","v.","提醒","Please remind me to do my homework.","请提醒我做作业。"),
            ("organize","ˈɔːrɡənaɪz","v.","组织","Let's organize a class meeting.","我们来组织一次班会。"),
            ("discuss","dɪˈskʌs","v.","讨论","Let's discuss this problem.","我们来讨论这个问题。"),
            ("solution","səˈluːʃn","n.","解决办法","We need to find a solution.","我们需要找到解决办法。"),
            ("respect","rɪˈspekt","v./n.","尊重","We should respect each other.","我们应该互相尊重。"),
            ("support","səˈpɔːrt","v./n.","支持","Thank you for your support.","谢谢你的支持。"),
        ],
        "patterns": [
            ("Let's + 动词原形", "提出建议", "<strong>Let's</strong> <span class=\"slot\">start the meeting</span>. / <strong>Let's</strong> <span class=\"slot\">help each other</span>."),
            ("Don't + 动词原形", "否定祈使句（禁止）", "<strong>Don't</strong> <span class=\"slot\">be late</span>. / <strong>Don't</strong> <span class=\"slot\">talk in class</span>."),
            ("How about + doing?", "委婉提建议", "<strong>How about</strong> <span class=\"slot\">making a plan</span>? / <strong>What about</strong> <span class=\"slot\">asking the teacher</span>?"),
        ],
        "grammar_title": "祈使句 & 提建议的多种表达",
        "grammar_sections": [
            ("祈使句", [
                ("类型","结构","示例"),
                ("肯定祈使句","动词原形开头","Sit down, please."),
                ("否定祈使句","Don't + 动词原形","Don't run in the hallways."),
                ("Let's 祈使句","Let's + 动词原形","Let's go home together."),
                ("礼貌祈使句","Please + 动词原形","Please open the door."),
            ]),
            ("提建议的多种方式", [
                ("表达","结构","示例"),
                ("Let's…","Let's + 动词","Let's clean the classroom."),
                ("How about…","How about + doing","How about taking a walk?"),
                ("Why not…","Why not + 动词","Why not ask for help?"),
                ("Shall we…","Shall we + 动词","Shall we start now?"),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="Don\'t to run in the hallways.">Don\'t to run in the hallways.</span>（Don\'t 后直接加动词原形）',
            '✅ <span class="correct" data-speak="Don\'t run in the hallways.">Don\'t run in the hallways.</span>',
            '❌ <span class="wrong" data-speak="How about to go shopping?">How about to go shopping?</span>（How about 后跟 doing）',
            '✅ <span class="correct" data-speak="How about going shopping?">How about going shopping?</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[祈使句] ____ (Don\'t / Not) be late for class.","Don't"),
            ("基础","★☆☆","[Let\'s] ____ ____ have a meeting this afternoon.","Let's"),
            ("基础","★☆☆","[选择] How about ____ (go / going) to the park?","going"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改写] You should not eat in class. (改为否定祈使句)","Don't eat in class."),
            ("提升","★★☆","[建议] We need to clean the room. (用 Let's 改写)","Let's clean the room."),
            ("提升","★★☆","[填空] ____ ____ (为什么不) ask your teacher for help?","Why not"),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 我们为什么不成立一个学习小组呢？","Why don't we set up a study group? / Why not set up a study group?"),
            ("挑战","★★★","[情景] 你的朋友上课总迟到，给出 2 条建议用不同句式。","自由回答，如：Let's set an alarm. / How about going to bed earlier?"),
        ],
        "reading_title": "How to Communicate Better",
        "reading_text": [
            "Do you sometimes find it hard to talk to others? Good communication skills can help. Here are some tips.",
            "First, listen carefully. Don't interrupt when others are speaking. Let them finish first.",
            "Second, use polite words. Say \"please\" and \"thank you\". Don't shout.",
            "Third, use \"I\" sentences. Say \"I feel sad when you ignore me\" instead of \"You always ignore me\". This helps people understand your feelings.",
            "Let's practice good communication every day!",
        ],
        "reading_gloss": [("communication","n. 沟通；交流"),("skill","n. 技能"),("interrupt","v. 打断"),("ignore","v. 忽视；不理睬"),("instead of","而不是")],
        "reading_qs": [
            ("阅读","★★☆","1. How many tips does the passage give?","Three."),
            ("阅读","★★☆","2. Why should we say \"I feel sad\" instead of \"You ignore me\"?","It helps people understand your feelings."),
            ("阅读","★★★","3. What is the first tip for good communication?","Listen carefully and don't interrupt."),
        ],
        "exam_q_type": "任务型阅读", "exam_q": "阅读短文，完成以下任务。",
        "exam_passage": ["We had a class meeting last Friday. The topic was \"How to make our class better\". (A) Let's read the suggestions. First, some students said: \"Don't leave trash in the classroom.\" (B) Second, \"Let's help each other with homework.\" (C) Also, \"How about planting some flowers on the windowsill?\" We all agreed these are good ideas. Let's make our class a better place together!"],
        "exam_options": [],
        "exam_answers": ["任务1：找出文中 3 个建议句式：<br>1. Don't leave trash (否定祈使句)<br>2. Let's help each other (Let's 建议)<br>3. How about planting... (How about 建议)<br>任务2：自由回答"],
        "writing_prompt": '假设你是班长，发现班里存在一些问题（乱扔垃圾、上课说话、作业拖拉），请写一封建议信给全班同学。',
        "writing_framework": ["开头：指出写信目的。","主体：列出 3 个问题+对应的建议（用 Let's/How about/Why not）。","结尾：鼓励大家一起行动。"],
        "writing_model_en": "Dear classmates, Let's make our class better! First, don't leave trash in the classroom. Please put it in the bin. Second, let's help each other with homework. We can form study groups. Third, how about keeping quiet when the teacher is speaking? Respect others. Let's work together and be the best class!",
        "writing_model_cn": "亲爱的同学们：让我们把班级变得更好！第一，不要把垃圾留在教室，请扔进垃圾桶。第二，让我们互相帮助做作业，可以结成学习小组。第三，老师讲话时保持安静。尊重他人。我们一起努力，成为最好的班级！",
        "project_title": "Class Communication Campaign",
        "project_desc": "和小组一起设计一份\"班级沟通改进计划\"，用英语列出 5 条沟通规则，并制作成海报。",
        "project_steps": ["讨论班级沟通中的问题。","针对每个问题提出改进规则。","用祈使句/Let's/How about 写出 5 条规则。","制作海报并在班里展示。"],
        "project_rubric": ["问题识别准确","规则用不同句式表达","海报设计美观","团队合作"],
        "checklist": ["我能用祈使句发出指令","我能用 Let's/How about 提建议","我能礼貌请求和回应","我能写建议信"],
        "feynman": "假装你是沟通培训师，给同学们上一节 2 分钟的\"如何有效沟通\"微课。练习祈使句和建议句式。",
        "review": ["用祈使句写 5 条班规","用 Let's/How about/Why not 各写 1 个建议","写一段关于沟通建议的短文","复习 where/when/how 疑问词"],
        "next_unit_title": "Time to Relax!",
        "next_unit_desc": "下一单元你将进入八年级下册，学习如何谈论休闲活动和放松方式。",
    },
}
