#!/usr/bin/env python3
"""Grade 8下册 (8 units) teaching content data."""

UNITS_8B = {
    "b2u01": {
        "num": "U1", "title": "Time to Relax!", "topic": "放松与娱乐",
        "en_topic": "Leisure Activities & Hobbies",
        "functions": "Talk about leisure activities and express preference",
        "grammar": "动词-ing 作主语和宾语 · enjoy/like/love/hate + doing",
        "writing": "My Favorite Way to Relax",
        "can_do": ["能用 enjoy/like/love/hate + doing 表达喜好","能用动词-ing 作主语谈论活动","能描述自己的休闲方式并给出理由","能写一篇关于放松方式的短文"],
        "dialogue_scene": "考试结束后，同学们讨论周末怎么放松。",
        "dialogue": [
            ("Amy","Finally, the exams are over! What do you like to do in your free time?","终于考完了！你空闲时间喜欢做什么？"),
            ("Ben","I love listening to music. It helps me relax. What about you?","我喜欢听音乐，能帮我放松。你呢？"),
            ("Amy","I enjoy reading novels. Reading is a great way to escape from stress.","我喜欢读小说。阅读是逃避压力的好方式。"),
            ("Ben","My sister hates staying at home on weekends. She always goes out with friends.","我妹妹讨厌周末待在家，她总是和朋友出去玩。"),
            ("Amy","Going out is fun, but staying home can be relaxing too. I like watching movies at home.","出去玩很有趣，但待在家里也很放松。我喜欢在家看电影。"),
            ("Ben","That sounds nice. Maybe I'll try reading a book this weekend for a change!","听起来不错。也许这周末我换换口味，读本书！"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>I love listening to music.</em> → <strong>love / like / enjoy / hate + doing</strong> 表达喜好。",
            "<strong>2.</strong> <em>Reading is a great way to escape.</em> → 动词-ing 作主语，谓语动词用三单：<strong>Reading is…</strong>",
            "<strong>3.</strong> <em>Going out is fun, but staying home can be relaxing too.</em> → 两个动词-ing 短语作主语对比。",
            "<strong>4.</strong> <em>I like watching movies at home.</em> → like doing (习惯性爱好) = like to do (偶尔想做)。",
        ],
        "vocab": [
            ("relax","rɪˈlæks","v.","放松","Listening to music helps me relax.","听音乐帮我放松。"),
            ("enjoy","ɪnˈdʒɔɪ","v.","享受；喜爱","I enjoy spending time with my family.","我喜欢和家人在一起。"),
            ("hate","heɪt","v.","讨厌","I hate getting up early on weekends.","我讨厌周末早起。"),
            ("novel","ˈnɑːvl","n.","小说","Reading novels is my hobby.","读小说是我的爱好。"),
            ("stress","stres","n.","压力","Too much stress is bad for health.","太多压力对健康不好。"),
            ("escape","ɪˈskeɪp","v.","逃避；摆脱","Reading helps me escape from stress.","阅读帮我摆脱压力。"),
            ("hobby","ˈhɑːbi","n.","爱好","Everyone needs a hobby.","每个人都需要一个爱好。"),
            ("lazy","ˈleɪzi","adj.","懒惰的","Don't be so lazy! Go out and play!","别这么懒！出去玩玩！"),
            ("active","ˈæktɪv","adj.","活跃的","My grandpa is still very active.","我爷爷仍然很活跃。"),
            ("collect","kəˈlekt","v.","收集","I enjoy collecting stamps.","我喜欢集邮。"),
        ],
        "patterns": [
            ("like / love / enjoy + doing", "表达喜好", "I <span class=\"slot\">enjoy reading</span> books. / She <span class=\"slot\">loves dancing</span>."),
            ("动词-ing 作主语", "把动作当话题", "<span class=\"slot\">Swimming</span> is good for health. / <span class=\"slot\">Playing chess</span> is fun."),
            ("hate / dislike + doing", "表达厌恶", "I <span class=\"slot\">hate getting up</span> early. / He <span class=\"slot\">dislikes watching</span> TV."),
        ],
        "grammar_title": "动词-ing 形式作主语和宾语",
        "grammar_sections": [
            ("动词-ing 作主语", [
                ("结构","示例","中文"),
                ("动词-ing + is/are…","Running is good exercise.","跑步是好的锻炼。"),
                ("It is + adj. + to do = Doing + is + adj.","It is fun to swim. = Swimming is fun.","游泳很有趣。"),
            ]),
            ("后接 doing 的常见动词", [
                ("动词","含义","示例"),
                ("enjoy","享受","I enjoy playing basketball."),
                ("like","喜欢","She likes singing."),
                ("love","热爱","He loves traveling."),
                ("hate","讨厌","They hate waiting."),
                ("finish","完成","I finished doing my homework."),
                ("keep","持续","Keep trying! Don't give up!"),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="I enjoy play basketball.">I enjoy play basketball.</span>（enjoy 后接 doing）',
            '✅ <span class="correct" data-speak="I enjoy playing basketball.">I enjoy playing basketball.</span>',
            '❌ <span class="wrong" data-speak="Play chess is interesting.">Play chess is interesting.</span>（动词原形不能作主语）',
            '✅ <span class="correct" data-speak="Playing chess is interesting.">Playing chess is interesting.</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[enjoy] I enjoy ____ (read) books in my free time.","reading"),
            ("基础","★☆☆","[hate] She hates ____ (get) up early on weekends.","getting"),
            ("基础","★☆☆","[主语] ____ (Swim) is good for your health.","Swimming"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改错] He like play basketball after school.","He likes playing basketball after school."),
            ("提升","★★☆","[句型] Playing computer games is fun. (改为同义句)<br>→ ____ is fun ____ play computer games.","It; to"),
            ("提升","★★☆","[填空] My brother finished ____ (do) his homework at 9 p.m.","doing"),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 跳舞和唱歌是她最喜欢做的事情。","Dancing and singing are her favorite things to do."),
            ("挑战","★★★","[补全] A: What do you enjoy doing in your free time?<br>B: ____","自由回答"),
        ],
        "reading_title": "How Teens Relax Around the World",
        "reading_text": [
            "Different teens have different ways to relax. Here are some examples.",
            "In Japan, many teens enjoy reading manga. It's a popular hobby. Some like drawing anime characters in their free time.",
            "In the UK, playing sports is very common. Teens love playing football, tennis, or swimming. Going to the park with friends is also a favorite activity.",
            "In China, listening to music and playing video games are popular. Some teens enjoy practicing calligraphy. It helps them relax and focus.",
            "No matter how you relax, taking a break is important for everyone!",
        ],
        "reading_gloss": [("manga","n. 漫画"),("anime","n. 动漫"),("common","adj. 常见的"),("calligraphy","n. 书法"),("focus","v. 集中注意力")],
        "reading_qs": [
            ("阅读","★★☆","1. What do Japanese teens enjoy reading?","Manga."),
            ("阅读","★★☆","2. What sports do UK teens like playing?","Football, tennis, or swimming."),
            ("阅读","★★★","3. Why do some Chinese teens practice calligraphy?","It helps them relax and focus."),
        ],
        "exam_q_type": "语法填空",
        "exam_q": "用括号内单词的适当形式填空。",
        "exam_passage": ["Everybody needs (1)____ (relax). In my family, we all have different ways. My father enjoys (2)____ (fish). My mother loves (3)____ (cook). (4)____ (Read) newspapers is her favorite. My sister likes (5)____ (draw). As for me, (6)____ (play) the guitar is the best way to relax."],
        "exam_options": [],
        "exam_answers": ["(1) to relax","(2) fishing","(3) cooking","(4) Reading","(5) drawing","(6) playing"],
        "writing_prompt": '请以"My Favorite Way to Relax"为题，写 70 词短文介绍你最喜欢的放松方式及理由。',
        "writing_framework": ["开头：你最喜欢的放松方式是什么。","主体：为什么喜欢（2-3 个理由）。","结尾：鼓励大家也试试。"],
        "writing_model_en": "My favorite way to relax is listening to music. I enjoy listening to pop music after doing homework. It makes me feel calm and happy. Also, singing along to the songs helps me practice English. Sometimes I share music with my friends. It's a great way to connect with them. Listening to music is really good for both body and mind!",
        "writing_model_cn": "我最喜欢的放松方式是听音乐。做完作业后我喜欢听流行音乐，让我感到平静和快乐。而且跟唱歌曲还能帮我练英语。有时我和朋友分享音乐，是和他们交流的好方式。听音乐真的对身心都好！",
        "project_title": "Leisure Time Survey & Report",
        "project_desc": "调查身边5位同学的休闲方式，用英语写一份调查报告，列出最受欢迎的 3 种活动。",
        "project_steps": ["设计调查问卷（列出 8 种常见休闲活动）。","采访 5 位同学。","统计结果并排名。","用英语写报告并展示。"],
        "project_rubric": ["数据真实","报告中正确使用动词-ing","排版清晰","展示流利"],
        "checklist": ["我能用 enjoy/like/love/hate + doing","我能用动词-ing 作主语","我能描述休闲方式及理由","我能写调查报告"],
        "feynman": "假装你在做一个关于\"全世界青少年如何放松\"的英语播客，介绍不同国家的休闲方式。",
        "review": ["用 enjoy/like/love/hate + doing 各写 1 句","用 3 个动词-ing 作主语的句子","写一段关于放松方式的话","复习动词-ing 的基本规则"],
        "next_unit_title": "Let's clean up!",
        "next_unit_desc": "下一单元你将学习如何用英语讨论环保行动，学会使用情态动词 should。",
    },

    "b2u02": {
        "num": "U2", "title": "Let's clean up!", "topic": "环保行动",
        "en_topic": "Environmental Protection", "functions": "Talk about environmental issues and volunteer work",
        "grammar": "情态动词 should / shouldn't ·动词短语（clean up, put up, give out）",
        "writing": "A Letter About Protecting the Environment",
        "can_do": ["能用 should/shouldn't 表达建议","能用动词短语描述环保行动","能谈论环境污染问题","能写一封环保倡议信"],
        "dialogue_scene": "班级讨论如何参与学校和社区的环保活动。",
        "dialogue": [
            ("Teacher","Our city is having a \"Clean Up Day\" this Saturday. What can we do?","这周六是城市清洁日。我们能做什么？"),
            ("Li Lei","We should clean up the park near our school. There is a lot of trash.","我们应该打扫学校附近的公园。那里有很多垃圾。"),
            ("Wang Fang","Good idea! We could also put up signs to ask people not to litter.","好主意！我们还可以张贴标语，请人们不要乱扔垃圾。"),
            ("Zhang Wei","I think we should give out leaflets to tell people about recycling.","我觉得应该发传单告诉大家关于回收的知识。"),
            ("Li Lei","We shouldn't use plastic bags. Let's bring our own bags when shopping.","我们不应该用塑料袋。购物时自带袋子。"),
            ("Teacher","Great suggestions! Let's meet at the school gate at 8 a.m. on Saturday. Let's clean up together!","好建议！周六早上 8 点校门口集合。一起行动！"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>We should clean up the park.</em> → <strong>should + 动词原形</strong> \"应该做\"，表建议。",
            "<strong>2.</strong> <em>We could also put up signs.</em> → <strong>could + 动词原形</strong> \"可以做\"，语气比 should 委婉。",
            "<strong>3.</strong> <em>We shouldn't use plastic bags.</em> → <strong>shouldn't + 动词原形</strong> \"不应该做\"。",
            "<strong>4.</strong> 动词短语：<strong>clean up</strong> 打扫干净 / <strong>put up</strong> 张贴 / <strong>give out</strong> 分发 / <strong>throw away</strong> 扔掉。",
        ],
        "vocab": [
            ("clean up","kliːn ʌp","phr.","打扫干净","Let's clean up the classroom.","让我们打扫教室。"),
            ("litter","ˈlɪtər","v.","乱扔垃圾","Don't litter in public places.","不要在公共场所乱扔垃圾。"),
            ("recycle","ˌriːˈsaɪkl","v.","回收利用","We should recycle paper and plastic.","我们应该回收纸张和塑料。"),
            ("plastic","ˈplæstɪk","n./adj.","塑料","Plastic pollution is a big problem.","塑料污染是个大问题。"),
            ("environment","ɪnˈvaɪrənmənt","n.","环境","We should protect the environment.","我们应该保护环境。"),
            ("volunteer","ˌvɑːlənˈtɪr","n./v.","志愿者；自愿","I want to volunteer for clean-up activities.","我想志愿参加清洁活动。"),
            ("leaflet","ˈliːflət","n.","传单","We gave out leaflets about recycling.","我们分发了关于回收的传单。"),
            ("sign","saɪn","n.","标志；标牌","Please put up a \"No Littering\" sign.","请张贴一个\"禁止乱扔垃圾\"的标志。"),
            ("pollute","pəˈluːt","v.","污染","Factories should not pollute the river.","工厂不应该污染河流。"),
            ("waste","weɪst","n./v.","浪费","Don't waste water. Turn off the tap.","不要浪费水。关掉水龙头。"),
        ],
        "patterns": [
            ("should / shouldn't + 动词原形", "表达应该/不应该", "We <span class=\"slot\">should save</span> water. / We <span class=\"slot\">shouldn't waste</span> food."),
            ("Let's + 动词短语", "提出行动建议", "Let's <span class=\"slot\">clean up</span> the park. / Let's <span class=\"slot\">put up</span> signs."),
            ("动词短语（v. + adv.）", "常见环保动词短语", "<span class=\"slot\">clean up</span> / <span class=\"slot\">give out</span> / <span class=\"slot\">throw away</span> / <span class=\"slot\">cut down</span>"),
        ],
        "grammar_title": "should / shouldn't + 动词短语",
        "grammar_sections": [
            ("should 的用法", [
                ("句式","结构","示例"),
                ("肯定","should + 动词原形","We should plant more trees."),
                ("否定","shouldn't + 动词原形","You shouldn't waste water."),
                ("疑问","Should + 主语 + 动词?","Should we clean the room?"),
            ]),
            ("常见动词短语", [
                ("短语","含义","示例"),
                ("clean up","打扫干净","Let's clean up the park."),
                ("put up","张贴；搭建","They put up a tent."),
                ("give out","分发","We gave out food to the poor."),
                ("cut down","砍倒","Don't cut down trees."),
                ("throw away","扔掉","Don't throw away old clothes."),
                ("pick up","捡起","Please pick up the trash."),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="We should to clean up.">We should to clean up.</span>（should 后不加 to）',
            '✅ <span class="correct" data-speak="We should clean up.">We should clean up.</span>',
            '❌ <span class="wrong" data-speak="Let\'s clean up it.">Let\'s clean up it.</span>（代词放短语中间：clean it up）',
            '✅ <span class="correct" data-speak="Let\'s clean it up.">Let\'s clean it up.</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[should] We ____ ____ (应该) protect the environment.","should"),
            ("基础","★☆☆","[shouldn't] You ____ ____ (不应该) waste food.","shouldn't"),
            ("基础","★☆☆","[短语] Please ____ ____ (捡起) the trash on the floor.","pick up"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改错] We should to recycle paper.","We should recycle paper."),
            ("提升","★★☆","[短语] 把代词放对位置：Please pick up it.","Please pick it up."),
            ("提升","★★☆","[填空] We shouldn\'t ____ ____ (砍倒) too many trees.","cut down"),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 我们应该怎么做来减少污染？","What should we do to reduce pollution?"),
            ("挑战","★★★","[补全] A: What should we do to help the environment?<br>B: ____","自由回答，如 We should plant more trees and recycle waste."),
        ],
        "reading_title": "Teens Who Make a Difference",
        "reading_text": [
            "Many teenagers around the world are helping to protect the environment.",
            "In China, a group of students started a \"No Plastic\" campaign at school. They asked students to bring their own water bottles. They also put up posters about plastic pollution.",
            "In Australia, a 14-year-old girl organized beach clean-ups every month. She and her friends picked up trash and recycled what they could.",
            "These teens show us that everyone can help. You don't need to be an adult to make a difference. Start small—clean up your neighborhood or plant a tree!",
        ],
        "reading_gloss": [("campaign","n. 运动；活动"),("poster","n. 海报"),("organize","v. 组织"),("adult","n. 成年人"),("neighborhood","n. 社区；街区")],
        "reading_qs": [
            ("阅读","★★☆","1. What did Chinese students ask others to do?","Bring their own water bottles."),
            ("阅读","★★☆","2. What did the Australian girl organize?","Monthly beach clean-ups."),
            ("阅读","★★★","3. What does the passage suggest we should do?","Start small—clean up your neighborhood or plant a tree."),
        ],
        "exam_q_type": "完形填空",
        "exam_q": "阅读短文，选择最佳选项。",
        "exam_passage": ["Our school had a \"Green Week\" last month. We (1)____ up the campus. We also (2)____ up posters about recycling. Students (3)____ throw away plastic bottles. Instead, they should (4)____ them. The best part was the tree-planting activity. We (5)____ 50 trees near the playground. Everyone felt happy. Small actions (6)____ make a big difference!"],
        "exam_options": [
            ("1.",{"A":"clean","B":"cleaned","C":"cleaning","D":"cleans"}),
            ("2.",{"A":"put","B":"puts","C":"putting","D":"putted"}),
            ("3.",{"A":"should","B":"shouldn't","C":"can","D":"will"}),
            ("4.",{"A":"recycle","B":"throw","C":"buy","D":"make"}),
            ("5.",{"A":"plant","B":"planted","C":"planting","D":"plants"}),
            ("6.",{"A":"can","B":"can't","C":"should","D":"shouldn't"}),
        ],
        "exam_answers": ["1. B (cleaned)","2. A (put)","3. B (shouldn't)","4. A (recycle)","5. B (planted)","6. A (can)"],
        "writing_prompt": '请以"Protecting Our Environment"为题，写一封 70 词的倡议信，号召同学们从身边小事做起保护环境。',
        "writing_framework": ["开头：指出环境问题的严重性。","主体：提出 3 条具体建议（用 should / shouldn't）。","结尾：号召大家一起行动。"],
        "writing_model_en": "Dear classmates, Our environment is in danger. We should do something to help. First, we shouldn't litter. Please put trash in the bin. Second, we should recycle paper and plastic. Third, we should plant more trees. Let's start from small things. Remember, a clean environment means a healthy life. Let's work together!",
        "writing_model_cn": "亲爱的同学们：我们的环境正面临威胁。我们应该做些事情来帮忙。第一，不要乱扔垃圾，请扔进垃圾桶。第二，我们应该回收纸张和塑料。第三，我们应该多种树。从小事做起。记住，干净的环境意味着健康的生活。一起行动吧！",
        "project_title": "Green Action Plan",
        "project_desc": "小组设计一份\"绿色行动计划\"(Green Action Plan)，列出在学校能做 5 件环保小事，并用 should/shouldn't 表达。",
        "project_steps": ["讨论学校有哪些环境问题。","列出 5 条改进措施。","用 should/shouldn't 写成行动清单。","做成海报在班里展示。"],
        "project_rubric": ["问题识别准确","措施具体可行","正确使用 should/shouldn't","排版美观"],
        "checklist": ["我能用 should/shouldn't 表达建议","我能用动词短语描述行动","我能谈论环境问题","我能写环保倡议信"],
        "feynman": "假装你是环保大使，用英语在全校大会上做 1 分钟演讲，呼吁大家保护环境。",
        "review": ["用 should/shouldn't 写 5 个句子","默写 8 个动词短语","写一段环保倡议","复习动词短语的代词位置"],
        "next_unit_title": "Could you please clean your room?",
        "next_unit_desc": "下一单元你学习如何礼貌地请求别人帮忙或允许自己做某事。",
    },

    "b2u03": {
        "num": "U3", "title": "Could you please clean your room?", "topic": "家务劳动",
        "en_topic": "Housework & Polite Requests",
        "functions": "Make polite requests and ask for permission",
        "grammar": "Could you please…? 礼貌请求 · Could I…? 请求许可 · 祈使句 vs 请求句",
        "writing": "A Note to a Family Member",
        "can_do": ["能用 Could you please… 礼貌请求","能用 Could I… 请求许可","能区分礼貌拒绝和接受","能写一张请求帮忙的便条"],
        "dialogue_scene": "周末早上，妈妈和 Mike 之间的对话。",
        "dialogue": [
            ("Mom","Mike, could you please clean your room? It's a mess!","Mike，请打扫下你的房间好吗？太乱了！"),
            ("Mike","Sure, Mom. I'll do it after breakfast. Could I play computer games after I finish?","好的妈妈。我吃完早饭就做。做完可以玩电脑游戏吗？"),
            ("Mom","Yes, you can. But could you also take out the trash?","可以。但你能顺便倒个垃圾吗？"),
            ("Mike","Of course. And could I invite Tom over this afternoon?","没问题。那我能邀请 Tom 下午来家里吗？"),
            ("Mom","I'm sorry, but we're going out this afternoon. How about this weekend?","抱歉，我们下午要出门。这周末怎么样？"),
            ("Mike","OK. Could you please help me with my math homework later?","好吧。那一会儿你能帮我辅导数学作业吗？"),
            ("Mom","Sure, I'd be happy to. Let's finish the chores first!","好的，很乐意。我们先做完家务！"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>Could you please clean your room?</em> → <strong>Could you please + 动词原形?</strong> 礼貌请求别人做某事。",
            "<strong>2.</strong> <em>Could I play computer games after I finish?</em> → <strong>Could I + 动词原形?</strong> 请求许可做某事。",
            "<strong>3.</strong> 肯定回答：<strong>Sure / Of course / Certainly.</strong> 否定回答：<strong>Sorry, but…</strong>",
            "<strong>4.</strong> <em>Could I invite Tom over?</em> → <strong>invite…over</strong> \"邀请……来家里\"。",
        ],
        "vocab": [
            ("mess","mes","n.","杂乱；混乱","Your room is a mess!","你的房间一团糟！"),
            ("trash","træʃ","n.","垃圾","Please take out the trash.","请把垃圾拿出去。"),
            ("fold","foʊld","v.","折叠","Could you fold the clothes?","你能叠衣服吗？"),
            ("sweep","swiːp","v.","扫；打扫","I swept the floor this morning.","我早上扫了地。"),
            ("chore","tʃɔːr","n.","家务杂事","I hate doing chores.","我讨厌做家务。"),
            ("invite","ɪnˈvaɪt","v.","邀请","Can I invite my friend over?","我能邀请朋友来吗？"),
            ("neither","ˈniːðər","pron./adv.","两者都不","Neither of us likes washing dishes.","我俩都不喜欢洗碗。"),
            ("hate","heɪt","v.","讨厌","I hate doing the laundry.","我讨厌洗衣服。"),
            ("fair","fer","adj.","公平的","It's not fair! I did all the work.","不公平！活都是我干的。"),
            ("depend","dɪˈpend","v.","依靠；取决于","That depends on how busy I am.","那取决于我有多忙。"),
        ],
        "patterns": [
            ("Could you please + 动词?", "礼貌请求别人做", "<strong>Could you please</strong> <span class=\"slot\">clean the table</span>?"),
            ("Could I + 动词?", "请求许可", "<strong>Could I</strong> <span class=\"slot\">use your phone</span>?"),
            ("Sure / Sorry, but…", "肯定/否定回应", "<span class=\"slot\">Sure</span> / <span class=\"slot\">Sorry, I'm busy</span>."),
        ],
        "grammar_title": "Could 礼貌请求与许可",
        "grammar_sections": [
            ("Could 请求句式对比", [
                ("句式","用途","示例"),
                ("Could you please + v.?","请求对方做某事","Could you please open the window?"),
                ("Could I + v.?","请求许可自己做","Could I borrow your pen?"),
                ("Can I + v.?","非正式请求许可","Can I have a glass of water?"),
            ]),
            ("肯定/否定回应", [
                ("肯定回应","否定回应"),
                ("Sure. / Of course.","Sorry, I'm afraid I can't."),
                ("Certainly.","I'm sorry, but I'm busy."),
                ("No problem.","I'd love to, but I can't."),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="Could you please to help me?">Could you please to help me?</span>（Could you please 后直接加动词原形）',
            '✅ <span class="correct" data-speak="Could you please help me?">Could you please help me?</span>',
            '❌ <span class="wrong" data-speak="Could I to go out?">Could I to go out?</span>（Could I 后直接加动词原形）',
            '✅ <span class="correct" data-speak="Could I go out?">Could I go out?</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[请求] ____ you please pass me the salt?","Could"),
            ("基础","★☆☆","[许可] ____ I use your dictionary? — Sure.","Could"),
            ("基础","★☆☆","[词义] Please ____ (拿出) the trash.","take out"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改错] Could you please to sweep the floor?","Could you please sweep the floor?"),
            ("提升","★★☆","[回应] A: Could I borrow your bike?<br>B: ____ (肯定的两种表达)","Sure. / Of course. / No problem."),
            ("提升","★★☆","[填空] Could you ____ (帮忙) me with the dishes?","help"),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 你能帮我叠一下衣服吗？——抱歉，我正忙着呢。","Could you please fold the clothes? — Sorry, I'm busy right now."),
            ("挑战","★★★","[情景] 你想借朋友的相机用一下，请写 2 句礼貌请求。","自由回答，如：Could I borrow your camera? I'll be very careful."),
        ],
        "reading_title": "Sharing Housework Makes a Happy Family",
        "reading_text": [
            "In many families, only parents do the housework. But sharing chores is important for everyone.",
            "Doing chores teaches children responsibility. When kids help with housework, they learn to take care of themselves and their home. It also makes parents feel less tired.",
            "In my family, everyone has a job. I sweep the floor and take out the trash. My brother does the dishes. My parents do the cooking and shopping.",
            "Sometimes I ask: \"Could I help with dinner?\" I enjoy learning to cook. Sharing housework is not just about cleaning—it's about caring for each other.",
        ],
        "reading_gloss": [("responsibility","n. 责任"),("take care of","照顾；负责"),("share","v. 分享；分担"),("caring","adj. 关爱的")],
        "reading_qs": [
            ("阅读","★★☆","1. What does the writer say about doing chores?","It teaches children responsibility."),
            ("阅读","★★☆","2. What chores does the writer do?","Sweep the floor and take out the trash."),
            ("阅读","★★★","3. What does sharing housework mean according to the writer?","It's about caring for each other."),
        ],
        "exam_q_type": "补全对话", "exam_q": "从方框中选择合适的句子补全对话。",
        "exam_passage": ["A: Mom, (1)________?<br>B: Sure, what is it?<br>A: (2)________ My friends are waiting for me.<br>B: I'm sorry, but you need to finish your homework first.<br>A: (3)________ I'll do it right after I come back.<br>B: OK then. (4)________<br>A: Thanks, Mom! I promise I'll finish it."],
        "exam_options": [],
        "exam_answers": ["(1) Could I go out to play?","(2) Could you please let me go now?","(3) Could I finish it later?","(4) But don't be too late."],
        "writing_prompt": '请给家人写一张便条(Note)，礼貌地请求他们帮忙做一件事（打扫房间、买东西等），用 Could you please。',
        "writing_framework": ["开头：称呼+礼貌请求。","主体：说明需要帮忙的事及原因。","结尾：提前感谢。"],
        "writing_model_en": "Dear Mom, Could you please help me buy some art supplies? I need colored paper and glue for my school project. It's due on Friday. I have basketball practice after school, so I can't go myself. Thank you so much! I'll finish my homework before dinner. Love, Tom",
        "writing_model_cn": "亲爱的妈妈：能帮我买些美术用品吗？学校项目需要彩纸和胶水，周五要交。我放学后有篮球训练，自己去不了。非常感谢！我会在晚饭前写完作业。爱你的 Tom",
        "project_title": "Polite Request Role-Play",
        "project_desc": "和搭档编写一段 6-8 轮的对话，场景自选（家里/学校/商店），必须用到 Could you please 和 Could I。",
        "project_steps": ["选择一个场景。","编写对话脚本（6-8 个来回）。","用不同颜色的笔标出请求句。","和搭档排练并在班里表演。"],
        "project_rubric": ["场景合理","包含 3 次以上 Could 请求","回应自然","表演流利有感情"],
        "checklist": ["我能用 Could you please 请求","我能用 Could I 请求许可","我能礼貌回应请求","我能写请求便条"],
        "feynman": "假装你是英语导游，用 Could you please 和 Could I 各造 3 个句子，演示如何在餐厅、商店、图书馆礼貌交流。",
        "review": ["用 Could you please 写 3 个请求句","用 Could I 写 3 个许可句","写一段家人间的请求对话","复习礼貌回应的多种表达"],
        "next_unit_title": "Why don't you talk to your parents?",
        "next_unit_desc": "下一单元你将学习如何用 Why don't you… 提出建议，谈论人际沟通中的问题。",
    },

    "b2u04": {
        "num": "U4", "title": "Why don't you talk to your parents?", "topic": "人际沟通",
        "en_topic": "Interpersonal Communication", "functions": "Give advice and talk about problems",
        "grammar": "Why don't you…? / Why not…? 提建议 · until / although / so that 连词",
        "writing": "Letter to Give Advice",
        "can_do": ["能用 Why don't you / Why not 提建议","能用 until / although / so that 连接句子","能描述人际矛盾并给出建议","能写一封建议信"],
        "dialogue_scene": "Li Ming 最近和好朋友闹矛盾了，向心理辅导员求助。",
        "dialogue": [
            ("Li Ming","I have a problem. My best friend is angry with me, but I don't know why.","我遇到一个问题。我最好的朋友生我的气了，但我不知道为什么。"),
            ("Counselor","I'm sorry to hear that. Why don't you talk to him directly?","听到这个我很难过。你为什么不直接和他谈谈呢？"),
            ("Li Ming","I tried, but he wouldn't listen. He didn't talk to me until yesterday.","我试过，但他不听。他直到昨天才和我说话。"),
            ("Counselor","Although he was angry, communication is important. Why don't you write him a letter?","虽然他在生气，但沟通很重要。你为什么不给他写封信呢？"),
            ("Li Ming","That's a good idea. I'll try it so that we can make up.","好主意。我试试，这样我们能和好。"),
            ("Counselor","You could also invite him to play basketball. Sports can help you relax and reconnect.","你也可以邀请他打篮球。运动能帮助放松和重新联系。"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>Why don't you talk to him directly?</em> → <strong>Why don't you + 动词原形?</strong> \"你为什么不……？\" 提建议。",
            "<strong>2.</strong> <em>He didn't talk to me until yesterday.</em> → <strong>not…until</strong> \"直到……才\"。",
            "<strong>3.</strong> <em>Although he was angry, communication is important.</em> → <strong>Although + 从句</strong> \"虽然……但是\"（不和 but 连用）。",
            "<strong>4.</strong> <em>I'll try it so that we can make up.</em> → <strong>so that</strong> \"以便\" 表目的。<strong>make up</strong> \"和好\"。",
        ],
        "vocab": [
            ("communicate","kəˈmjuːnɪkeɪt","v.","沟通；交流","We need to communicate with each other.","我们需要互相沟通。"),
            ("directly","dəˈrektli","adv.","直接地","Talk to him directly.","直接跟他谈谈。"),
            ("although","ɔːlˈðoʊ","conj.","虽然；尽管","Although it's hard, you should try.","虽然很难，但你应尝试。"),
            ("until","ənˈtɪl","conj./prep.","直到","I will wait until you come back.","我会等到你回来。"),
            ("advice","ədˈvaɪs","n.","建议","Can you give me some advice?","你能给我一些建议吗？"),
            ("argue","ˈɑːrɡjuː","v.","争论；争吵","Don't argue with your parents.","不要和父母争吵。"),
            ("proper","ˈprɑːpər","adj.","合适的；恰当的","We should find a proper time to talk.","我们应该找个合适的时间谈谈。"),
            ("explain","ɪkˈspleɪn","v.","解释","Let me explain how I feel.","让我解释我的感受。"),
            ("relation","rɪˈleɪʃn","n.","关系","Good relations need good communication.","好的关系需要好的沟通。"),
            ("offer","ˈɔːfər","v.","提供；主动提出","He offered to help me.","他主动提出帮我。"),
        ],
        "patterns": [
            ("Why don't you + 动词?", "提建议", "<strong>Why don't you</strong> <span class=\"slot\">talk to him</span>?"),
            ("Why not + 动词?", "提建议（省略式）", "<strong>Why not</strong> <span class=\"slot\">try again</span>?"),
            ("not…until…", "直到……才", "He <strong>didn't</strong> come <strong>until</strong> <span class=\"slot\">8 o'clock</span>."),
            ("Although…, …", "虽然……但是", "<strong>Although</strong> <span class=\"slot\">it's hard</span>, you should keep trying."),
        ],
        "grammar_title": "提建议 & until/although/so that",
        "grammar_sections": [
            ("提建议的多种方式", [
                ("表达","结构","示例"),
                ("Why don't you…","Why don't you + v.","Why don't you ask your teacher?"),
                ("Why not…","Why not + v.","Why not have a rest?"),
                ("You should…","You should + v.","You should talk to your parents."),
                ("You could…","You could + v.","You could write a letter."),
            ]),
            ("连词 until/although/so that", [
                ("连词","含义","示例"),
                ("until","直到","Wait until I come back."),
                ("not…until","直到……才","He didn't sleep until 11 p.m."),
                ("although","虽然","Although he was tired, he kept working."),
                ("so that","以便","I got up early so that I could catch the bus."),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="Although he is busy, but he helps me.">Although he is busy, but he helps me.</span>（although 和 but 不能连用）',
            '✅ <span class="correct" data-speak="Although he is busy, he helps me.">Although he is busy, he helps me.</span>',
            '❌ <span class="wrong" data-speak="Why don\'t you to ask him?">Why don\'t you to ask him?</span>（Why don\'t you 后加动词原形）',
            '✅ <span class="correct" data-speak="Why don\'t you ask him?">Why don\'t you ask him?</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[建议] ____ ____ you ask your teacher for help?","Why don't"),
            ("基础","★☆☆","[until] I will wait ____ you come back.","until"),
            ("基础","★☆☆","[although] ____ it rained, we still went out.","Although"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改错] Why not to go with us?","Why not go with us?"),
            ("提升","★★☆","[连词] I woke up early ____ ____ (以便) I could catch the first bus.","so that"),
            ("提升","★★☆","[句型] He didn't sleep until midnight. (改为肯定句)","He slept at midnight."),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 虽然作业很难，但我一直坚持到了最后。","Although the homework was hard, I kept trying until the end."),
            ("挑战","★★★","[补全] A: I argued with my best friend.<br>B: ____ ____ ____ call her and say sorry?","Why don't you"),
        ],
        "reading_title": "How to Deal with Friendship Problems",
        "reading_text": [
            "Friendship is important, but problems can happen. Here are some tips to handle them.",
            "First, stay calm. Don't argue when you're angry. Take a deep breath and wait until you feel better.",
            "Second, talk about your feelings. Use \"I\" sentences. Say \"I felt sad when you ignored me\" instead of \"You always ignore me.\"",
            "Third, try to understand your friend's point of view. Although you may disagree, respect each other's feelings.",
            "Finally, why not do something fun together? Playing sports or watching a movie can help you reconnect.",
        ],
        "reading_gloss": [("deal with","处理；应对"),("handle","v. 处理"),("calm","adj. 冷静的"),("point of view","观点；立场"),("reconnect","v. 重新建立联系")],
        "reading_qs": [
            ("阅读","★★☆","1. What shouldn't you do when you're angry?","Argue."),
            ("阅读","★★☆","2. What kind of sentences should you use to talk about feelings?","\"I\" sentences."),
            ("阅读","★★★","3. Why should you try to understand your friend's point of view?","Because although you may disagree, you should respect each other's feelings."),
        ],
        "exam_q_type": "语法填空", "exam_q": "用括号内连词或所给词的适当形式填空。",
        "exam_passage": ["(1)____ (Although / Because) my sister is younger, she often gives me good advice. Last week, I (2)____ (argue) with my best friend. My sister said, \"Why (3)____ you call her?\" I followed her advice. (4)____ (Although / Until) I was nervous, I made the call. My friend and I talked (5)____ (until / unless) we understood each other. We made up in the end."],
        "exam_options": [],
        "exam_answers": ["(1) Although","(2) argued","(3) don't","(4) Although","(5) until"],
        "writing_prompt": "你的朋友和妈妈吵架了，很伤心。请给他/她写一封 70 词的建议信，用到 Why don't you 和 although。",
        "writing_framework": ["开头：表达理解和关心。","主体：给出 2 条具体建议（用 Why don't you）。","结尾：鼓励和祝福。"],
        "writing_model_en": "Dear friend, I'm sorry to hear about your problem. Although your mom was angry, I believe she loves you. Why don't you talk to her when she is calm? You could say sorry first. Why not help with some housework to show you care? Good communication can solve many problems. I hope you and your mom can make up soon!",
        "writing_model_cn": "亲爱的朋友：听说你的问题我很难过。虽然你妈妈在生气，但我相信她爱你。你为什么不趁她冷静的时候和她谈谈？你可以先道歉。为什么不帮她做些家务来表现你的关心？好的沟通能解决很多问题。希望你们能尽快和好！",
        "project_title": "Agony Aunt Role-Play",
        "project_desc": "小组扮演\"知心姐姐\"(Agony Aunt)和求助者，A 描述一个生活中的难题，B 用 Why don't you / Why not / You should 给出建议。",
        "project_steps": ["A 准备一个生活中的人际难题。","B 用至少 3 种不同句式给出建议。","写在展示卡上。","全班面前表演。"],
        "project_rubric": ["问题真实可信","给出 3 条以上建议","用了 3 种不同建议句式","表演有表现力"],
        "checklist": ["我能用 Why don't you 和 Why not 提建议","我能用 until/although/so that","我能描述人际问题并给建议","我能写建议信"],
        "feynman": "假装你是心理咨询师(Agony Aunt)，用英语回答听众来信中的问题，用 Why don't you 和 Why not 给出建议。",
        "review": ["用 Why don't you 写 3 个建议","用 Why not 写 3 个建议","用 until/although/so that 各写 1 句","写一段处理朋友矛盾的对话"],
        "next_unit_title": "What were you doing when the rainstorm came?",
        "next_unit_desc": "下一单元你将学习过去进行时(was/were doing)，描述过去某个时刻正在发生的事情。",
    },

    "b2u05": {
        "num": "U5", "title": "What were you doing when the rainstorm came?", "topic": "过去进行",
        "en_topic": "Past Continuous Tense", "functions": "Talk about what was happening at a specific past time",
        "grammar": "过去进行时（was/were + doing）· when / while 引导时间状语从句",
        "writing": "An Unforgettable Moment",
        "can_do": ["能用 was/were doing 描述过去某刻正在做的事","能用 when 和 while 连接时间状语从句","能区分过去进行时和一般过去时","能写一段难忘时刻的短文"],
        "dialogue_scene": "暴风雨过后，同学们分享昨天下午暴风雨来临时他们在做什么。",
        "dialogue": [
            ("Lisa","What were you doing when the rainstorm came yesterday?","昨天暴风雨来的时候你在做什么？"),
            ("Tom","I was playing basketball in the gym. We stopped immediately when we heard the thunder.","我在体育馆打篮球。听到雷声我们立刻停下了。"),
            ("Lisa","I was doing my homework in my room. While I was writing, the lights went out!","我在房间写作业。正写着，灯灭了！"),
            ("Amy","I was walking home from school. I was carrying an umbrella, but it was no use!","我正从学校走回家。我带了伞，但根本没用！"),
            ("Tom","Were you scared?","你害怕吗？"),
            ("Amy","Yes, I was. While I was running, I fell and got wet all over.","是的。我跑的时候摔倒了，全身都湿了。"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>What were you doing when the rainstorm came?</em> → 过去进行时问句：<strong>What + was/were + 主语 + doing + when…?</strong>",
            "<strong>2.</strong> <em>I was playing basketball when the rainstorm came.</em> → 长动作（was playing）被短动作（came）打断，用 when。",
            "<strong>3.</strong> <em>While I was writing, the lights went out.</em> → <strong>while + 过去进行时</strong> 表示\"在做某事期间\"。",
            "<strong>4.</strong> <em>While I was running, I fell.</em> → while 从句用过去进行时，主句用一般过去时。",
        ],
        "vocab": [
            ("rainstorm","ˈreɪnstɔːrm","n.","暴风雨","The rainstorm lasted for two hours.","暴风雨持续了两小时。"),
            ("alarm","əˈlɑːrm","n.","闹钟；警报","I didn't hear the alarm this morning.","今早我没听到闹钟。"),
            ("begin","bɪˈɡɪn","v.","开始","The storm began at 4 p.m.","暴风雨下午 4 点开始。"),
            ("heavily","ˈhevɪli","adv.","大量地；沉重地","It was raining heavily outside.","外面下着大雨。"),
            ("suddenly","ˈsʌdənli","adv.","突然","Suddenly, the lights went out.","突然，灯灭了。"),
            ("strange","streɪndʒ","adj.","奇怪的","I heard a strange noise.","我听到一个奇怪的声音。"),
            ("report","rɪˈpɔːrt","v./n.","报道；报告","The weather report said there would be a storm.","天气预报说有暴风雨。"),
            ("area","ˈeriə","n.","地区；区域","Many areas were flooded.","很多地区被淹了。"),
            ("wind","wɪnd","n.","风","The wind was blowing strongly.","风很大。"),
            ("fallen","ˈfɔːlən","adj.","倒下的；落下的","There were fallen trees on the road.","路上有倒下的树。"),
        ],
        "patterns": [
            ("was/were + doing", "过去进行时基本结构", "I <span class=\"slot\">was reading</span> at 8 p.m. / They <span class=\"slot\">were playing</span> soccer then."),
            ("…when…（when + 一般过去时）", "长动作被短动作打断", "I <span class=\"slot\">was sleeping when</span> the phone rang."),
            ("…while…（while + 过去进行时）", "两个动作同时进行", "She <span class=\"slot\">was cooking while</span> he was watching TV."),
        ],
        "grammar_title": "过去进行时（was/were + doing）",
        "grammar_sections": [
            ("过去进行时的构成", [
                ("人称","was/were","动词形式","示例"),
                ("I / He / She / It","was","doing","I was sleeping."),
                ("We / You / They","were","doing","They were running."),
            ]),
            ("when vs while", [
                ("连词","用法","示例"),
                ("when","+ 短暂性动词（一般过去时）","I was eating when he came."),
                ("when","+ 延续性动词（过去进行时）","When I was sleeping, someone knocked."),
                ("while","+ 延续性动词（过去进行时）","While I was walking, it started to rain."),
                ("while","+ 两个同时进行的动作","He was singing while she was dancing."),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="I was play basketball when it rained.">I was play basketball when it rained.</span>（过去进行时要加 -ing）',
            '✅ <span class="correct" data-speak="I was playing basketball when it rained.">I was playing basketball when it rained.</span>',
            '❌ <span class="wrong" data-speak="While I watched TV, my mom was cooking.">While I watched TV, my mom was cooking.</span>（while 后多用进行时）',
            '✅ <span class="correct" data-speak="While I was watching TV, my mom was cooking.">While I was watching TV, my mom was cooking.</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[过去进行] I ____ (watch) TV at 8 p.m. last night.","was watching"),
            ("基础","★☆☆","[过去进行] They ____ (play) football when it started to rain.","were playing"),
            ("基础","★☆☆","[选择] ____ (When / While) I was reading, the phone rang.","When / While (均可，注意用法)"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改错] We was having dinner when the lights went out.","We were having dinner when the lights went out."),
            ("提升","★★☆","[句型] I was sleeping. The doorbell rang. (合并)","I was sleeping when the doorbell rang."),
            ("提升","★★☆","[填空] While I ____ (walk) home, I met an old friend.","was walking"),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 昨天下午 3 点你在做什么？我正在图书馆看书。","What were you doing at 3 p.m. yesterday? I was reading in the library."),
            ("挑战","★★★","[补全] A: I called you at 7 p.m. but nobody answered.<br>B: Oh, I ____ ____ (take) a shower at that time.","was taking"),
        ],
        "reading_title": "The Day the Storm Came",
        "reading_text": [
            "Last summer, a terrible storm hit our town. I will never forget that afternoon.",
            "I was doing my homework when dark clouds started to cover the sky. While I was looking out of the window, the wind began to blow heavily. Trees were swaying. Soon, the rain was pouring down.",
            "My mom was cooking in the kitchen. My dad was trying to close all the windows. I felt a little scared.",
            "After the storm, we went outside. There were fallen branches everywhere. But our neighbors were already helping each other clean up. Although the storm was strong, our community was stronger.",
        ],
        "reading_gloss": [("hit","v. 袭击"),("cloud","n. 云"),("cover","v. 覆盖"),("sway","v. 摇摆"),("pour","v. 倾泻"),("branch","n. 树枝"),("community","n. 社区")],
        "reading_qs": [
            ("阅读","★★☆","1. What was the writer doing when dark clouds appeared?","Doing homework."),
            ("阅读","★★☆","2. What was the writer's mom doing during the storm?","Cooking in the kitchen."),
            ("阅读","★★★","3. What did the writer see after the storm?","Fallen branches everywhere and neighbors helping each other clean up."),
        ],
        "exam_q_type": "完形填空",
        "exam_q": "阅读短文，选择最佳选项。",
        "exam_passage": ["Yesterday at 6 p.m., a fire alarm (1)____ in our building. I (2)____ my homework. My mom (3)____ dinner in the kitchen. We quickly went outside. While we (4)____ for the firefighters, I saw my neighbor helping an old lady down the stairs. Everyone was safe in the end. While the firefighters (5)____ the fire, we waited outside."],
        "exam_options": [
            ("1.",{"A":"go off","B":"went off","C":"going off","D":"goes off"}),
            ("2.",{"A":"do","B":"did","C":"was doing","D":"am doing"}),
            ("3.",{"A":"was cooking","B":"cooking","C":"cooks","D":"cooked"}),
            ("4.",{"A":"wait","B":"waited","C":"were waiting","D":"are waiting"}),
            ("5.",{"A":"puts out","B":"putting out","C":"were putting out","D":"are putting out"}),
        ],
        "exam_answers": ["1. B (went off)","2. C (was doing)","3. A (was cooking)","4. C (were waiting)","5. C (were putting out)"],
        "writing_prompt": '请以"An Unforgettable Moment"为题，写 70 词短文描述一个你难忘的时刻（用过去进行时）。',
        "writing_framework": ["开头：时间+地点+事件背景。","主体：当时你在做什么（过去进行时）。","结尾：你的感受和收获。"],
        "writing_model_en": "I will never forget the moment I won first prize in the English speech contest. When the host announced my name, I was sitting in my seat and my heart was beating fast. While I was walking to the stage, I could feel everyone's eyes on me. I took a deep breath and started my speech. When I finished, everyone was clapping. It was the best moment of my life!",
        "writing_model_cn": "我永远不会忘记英语演讲比赛得一等奖的那一刻。主持人宣布我的名字时，我正坐在座位上，心跳加速。上台时，我能感到所有人的目光。我深吸一口气开始了演讲。结束时，所有人都在鼓掌。那是我人生中最美好的一刻！",
        "project_title": "News Report: What Were People Doing?",
        "project_desc": "模拟一个新闻事件（火灾/地震/暴风雨），采访 3 位\"目击者\"（同学扮演），询问事件发生时他们在做什么。",
        "project_steps": ["小组选择一个\"新闻事件\"。","一人当记者，三人当目击者。","记者准备采访问题（用过去进行时）。","排练并在班里展示。"],
        "project_rubric": ["事件设定合理","采访使用过去进行时","目击者回答详细","展示有新闻效果"],
        "checklist": ["我能用 was/were doing 表达","我能用 when/while 连接句子","我能区分一般过去时和过去进行时","我能描述难忘时刻"],
        "feynman": "假装你是新闻记者，用英语报道昨天下午 3 点发生的事件，采访 3 个\"目击者\"当时在做什么。",
        "review": ["用 was/were doing 写 5 个句子","用 when 和 while 各写 2 个从句","改写 5 个一般过去时为过去进行时","写一段你在做的事被打断的经历"],
        "next_unit_title": "An old man tried to move the mountains.",
        "next_unit_desc": "下一单元你将学习如何用英语讲故事，包括连词 unless / as soon as / so…that。",
    },

    "b2u06": {
        "num": "U6", "title": "An old man tried to move the mountains.", "topic": "故事传说",
        "en_topic": "Stories & Legends", "functions": "Tell stories using conjunctions",
        "grammar": "unless / as soon as / so…that 连词 · 一般过去时叙事",
        "writing": "My Favorite Story",
        "can_do": ["能用 unless 表示条件","能用 as soon as 表示\"一……就\"","能用 so…that 表示结果","能用英语复述一个故事"],
        "dialogue_scene": "语文课上，同学们在讨论中国民间故事《愚公移山》。",
        "dialogue": [
            ("Teacher","What do you think of the story \"Yu Gong Moves a Mountain\"?","你们觉得《愚公移山》这个故事怎么样？"),
            ("Wang Lin","I think it's amazing! The old man never gave up. He kept trying until the end.","我觉得很了不起！老人从不放弃，一直坚持到底。"),
            ("Li Mei","I agree. The story tells us: Unless we try, we will never know what we can do.","我同意。这个故事告诉我们：不去尝试就永远不会知道自己的能力。"),
            ("Zhang Wei","But I think it's a bit silly. Why didn't he just move to a new place?","但我觉得有点傻。他为什么不直接搬家呢？"),
            ("Teacher","Good point! The story is not about moving mountains. It's about the spirit of never giving up.","说得好！这个故事不是关于搬山，而是永不放弃的精神。"),
            ("Wang Lin","As soon as I heard this story, I thought of my grandpa. He never gives up either.","我一听到这个故事就想起了我爷爷。他也从不放弃。"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>Unless we try, we will never know what we can do.</em> → <strong>unless</strong> = if not \"如果不\"，引导条件状语从句。",
            "<strong>2.</strong> <em>As soon as I heard this story, I thought of my grandpa.</em> → <strong>as soon as</strong> \"一……就\"。",
            "<strong>3.</strong> <em>The old man never gave up.</em> → <strong>give up</strong> \"放弃\"，代词放中间：give it up。",
            "<strong>4.</strong> <em>He kept trying until the end.</em> → <strong>keep doing</strong> \"持续做某事\"。",
        ],
        "vocab": [
            ("move","muːv","v.","移动；搬动","The old man tried to move the mountains.","老人试图搬山。"),
            ("stone","stoʊn","n.","石头","There were big stones on the road.","路上有大石头。"),
            ("weak","wiːk","adj.","虚弱的；弱的","He was too weak to carry the box.","他太虚弱搬不动箱子。"),
            ("once","wʌns","adv.","一旦；曾经","Once upon a time, there was an old man.","从前有一位老人。"),
            ("fit","fɪt","v./adj.","适合；健康的","Keep trying until you find a way that fits.","不断尝试直到找到合适的方法。"),
            ("spirit","ˈspɪrɪt","n.","精神","The story shows the spirit of never giving up.","这个故事展现了永不放弃的精神。"),
            ("object","ˈɑːbdʒɪkt","v.","反对","Nobody objected to his plan.","没人反对他的计划。"),
            ("clever","ˈklevər","adj.","聪明的","The monkey is very clever.","猴子非常聪明。"),
            ("stupid","ˈstuːpɪd","adj.","愚蠢的","Some people thought he was stupid.","有些人觉得他很蠢。"),
            ("magic","ˈmædʒɪk","adj./n.","魔法的；魔法","The magic stick could change size.","金箍棒能改变大小。"),
        ],
        "patterns": [
            ("unless + 从句", "如果不；除非", "<strong>Unless</strong> <span class=\"slot\">you work hard</span>, you won't succeed."),
            ("as soon as + 从句", "一……就……", "<strong>As soon as</strong> <span class=\"slot\">I got home</span>, I started my homework."),
            ("so + adj. + that + 从句", "如此……以至于", "The mountain was <strong>so</strong> <span class=\"slot\">high</span> <strong>that</strong> <span class=\"slot\">few people could climb it</span>."),
        ],
        "grammar_title": "unless / as soon as / so…that",
        "grammar_sections": [
            ("三个连词", [
                ("连词","含义","示例"),
                ("unless","如果不，除非","You'll be late unless you hurry."),
                ("as soon as","一……就……","I'll call you as soon as I arrive."),
                ("so…that…","如此……以致","The box was so heavy that I couldn't carry it."),
            ]),
            ("unless = if not", [
                ("unless 句子","= if not 句子"),
                ("You won't pass unless you study.","= You won't pass if you don't study."),
                ("I'll go unless it rains.","= I'll go if it doesn't rain."),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="Unless you will study, you will fail.">Unless you will study, you will fail.</span>（unless 从句用一般现在时表将来）',
            '✅ <span class="correct" data-speak="Unless you study, you will fail.">Unless you study, you will fail.</span>',
            '❌ <span class="wrong" data-speak="As soon as I will get home, I will call you.">As soon as I will get home, I will call you.</span>（as soon as 从句用一般现在时表将来）',
            '✅ <span class="correct" data-speak="As soon as I get home, I will call you.">As soon as I get home, I will call you.</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[unless] You won't succeed ____ you work hard.","unless"),
            ("基础","★☆☆","[as soon as] Call me ____ you arrive.","as soon as"),
            ("基础","★☆☆","[so…that] The story was ____ interesting ____ everyone loved it.","so; that"),
        ],
        "mid_qs": [
            ("提升","★★☆","[同义句] Unless you start now, you will miss the bus.<br>= ____ you ____ start now, you will miss the bus.","If; don't"),
            ("提升","★★☆","[改错] As soon as she will come, tell me.","As soon as she comes, tell me."),
            ("提升","★★☆","[填空] The mountain was ____ high ____ nobody could climb it.","so; that"),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 除非你不断尝试，否则你永远不会知道你能做什么。","Unless you keep trying, you will never know what you can do."),
            ("挑战","★★★","[复述] 用英语简单复述《愚公移山》的故事（3-5 句）。","Once upon a time, an old man tried to move two big mountains. He kept digging every day. People laughed at him, but he didn't give up. Finally, the gods were moved and helped him."),
        ],
        "reading_title": "The Magic Paintbrush",
        "reading_text": [
            "Once upon a time, there was a poor boy named Ma Liang. He loved painting but had no brush.",
            "One night, an old man appeared in his dream and gave him a magic paintbrush. As soon as Ma Liang woke up, he found the brush beside his bed.",
            "He painted a bird and the bird came to life! He was so happy that he painted food for the poor people.",
            "A rich man heard about the brush. \"Paint me a gold tree!\" he ordered. \"Unless you paint it, I will put you in jail.\"",
            "Ma Liang refused. As soon as the rich man tried to take the brush, Ma Liang painted a big river. The rich man was washed away and never came back.",
        ],
        "reading_gloss": [("paintbrush","n. 画笔"),("appear","v. 出现"),("come to life","活过来"),("refuse","v. 拒绝"),("jail","n. 监狱"),("wash away","冲走")],
        "reading_qs": [
            ("阅读","★★☆","1. What did the old man give Ma Liang?","A magic paintbrush."),
            ("阅读","★★☆","2. What did Ma Liang paint for the poor people?","Food."),
            ("阅读","★★★","3. How did Ma Liang escape from the rich man?","He painted a big river that washed the rich man away."),
        ],
        "exam_q_type": "语法填空", "exam_q": "用括号内所给词或连词的适当形式填空。",
        "exam_passage": ["Once upon a time, an old man (1)____ (try) to move the mountains. His family (2)____ (help) him every day. A clever man said, \"You are (3)____ (silly) old man. (4)____ you stop, you will never finish.\" The old man replied, \"(5)____ I die, my children will continue. (6)____ (unless / as soon as) we keep trying, the mountains will become smaller.\" Finally, the gods (7)____ (move) by his spirit and took the mountains away."],
        "exam_options": [],
        "exam_answers": ["(1) tried","(2) helped","(3) a silly","(4) Unless","(5) After / When","(6) As long as","(7) were moved"],
        "writing_prompt": '请以"My Favorite Story"为题，写 70 词介绍你最喜欢的一个故事，用 unless / as soon as / so…that 中的至少两个。',
        "writing_framework": ["开头：故事名称和来源。","主体：故事大意（用 as soon as / unless 等）。","结尾：你喜欢的原因。"],
        "writing_model_en": "My favorite story is \"The Fox and the Grapes.\" A fox was so hungry that he wanted to eat some grapes. But the grapes were so high that he couldn't reach them. He tried again and again. As soon as he jumped, the grapes moved away in the wind. Finally, he gave up and said, \"The grapes are sour.\" I like this story because it teaches us not to make excuses when we fail.",
        "writing_model_cn": "我最喜欢的故事是《狐狸和葡萄》。一只狐狸很饿想吃葡萄，但葡萄太高够不着。他试了一次又一次，一跳葡萄就被风吹开。最后他放弃说\"葡萄是酸的\"。我喜欢这个故事因为它教我们失败时不要找借口。",
        "project_title": "Storytelling Show",
        "project_desc": "小组选择一个中国或西方民间故事，用英语改编表演 3 分钟短剧，用到 unless / as soon as / so…that。",
        "project_steps": ["选一个故事。","分配角色和台词。","在台词中加入 unless / as soon as / so…that。","准备道具并在班里表演。"],
        "project_rubric": ["故事完整","正确使用连词","角色表现力强","团队合作好"],
        "checklist": ["我能用 unless 表示条件","我能用 as soon as 连接动作","我能用 so…that 表示结果","我能用英语复述故事"],
        "feynman": "假装你是\"故事大王\"，用英语给同学讲一个中国民间故事，用到 unless 和 as soon as。",
        "review": ["用 unless 写 3 个句子","用 as soon as 写 3 个句子","用 so…that 写 3 个句子","用英语写一个 50 词的小故事"],
        "next_unit_title": "What's the highest mountain in the world?",
        "next_unit_desc": "下一单元你将学习形容词和副词的比较级、最高级在描述世界之最中的应用。",
    },

    "b2u07": {
        "num": "U7", "title": "What's the highest mountain in the world?", "topic": "世界之最",
        "en_topic": "Geographic Facts & Superlatives", "functions": "Talk about geographic features using comparatives and superlatives",
        "grammar": "形容词/副词比较级与最高级的深入运用 · 数字表达（长/宽/高/深等）",
        "writing": "Amazing Places in China",
        "can_do": ["能用最高级描述地理特征","能用数字表达长度/高度/深度","能比较不同地理特征","能介绍一处世界之最"],
        "dialogue_scene": "地理课上，老师在用英语介绍世界地理之最。",
        "dialogue": [
            ("Teacher","What's the highest mountain in the world?","世界上最高的山是什么？"),
            ("Li Wei","Mount Qomolangma! It's 8,848.86 meters high.","珠穆朗玛峰！高 8848.86 米。"),
            ("Teacher","Correct! And what's the longest river in China?","正确！中国最长的河是什么？"),
            ("Wang Fang","The Yangtze River. It's about 6,300 kilometers long.","长江。长约 6300 公里。"),
            ("Teacher","Very good. The Caspian Sea is the deepest lake in the world. It's 1,025 meters deep.","很好。里海是世界上最深的湖，深 1025 米。"),
            ("Zhang Wei","Is the Sahara the biggest desert?","撒哈拉是最大的沙漠吗？"),
            ("Teacher","The Sahara is the hottest desert. The largest desert in the world is Antarctica!","撒哈拉是最热的沙漠。世界上最大的沙漠是南极洲！"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>It's 8,848.86 meters high.</em> → 数字 + 单位 + adj.：<strong>meters high / kilometers long / meters deep</strong>。",
            "<strong>2.</strong> <em>What's the longest river in China?</em> → <strong>the + 最高级 + 名词 + in + 范围</strong>。",
            "<strong>3.</strong> <em>The Caspian Sea is the deepest lake.</em> → <strong>deep → deepest</strong> 。",
            "<strong>4.</strong> 数字读法：8,848.86 → <strong>eight thousand eight hundred forty-eight point eight six</strong>。",
        ],
        "vocab": [
            ("mountain","ˈmaʊntn","n.","山；山脉","Mount Qomolangma is the highest mountain.","珠穆朗玛峰是最高峰。"),
            ("deep","diːp","adj.","深的","The Pacific Ocean is very deep.","太平洋很深。"),
            ("desert","ˈdezərt","n.","沙漠","The Sahara is the hottest desert.","撒哈拉是最热的沙漠。"),
            ("population","ˌpɑːpjuˈleɪʃn","n.","人口","China has the largest population.","中国人口最多。"),
            ("include","ɪnˈkluːd","v.","包括","Wild animals include tigers and pandas.","野生动物包括老虎和熊猫。"),
            ("protection","prəˈtekʃn","n.","保护","We need to take action for the protection of animals.","我们需要采取行动保护动物。"),
            ("inch","ɪntʃ","n.","英寸","The baby panda weighs about 0.1 kilos at birth.","熊猫宝宝出生时约 0.1 公斤。"),
            ("weigh","weɪ","v.","重（多少）","An adult panda weighs about 100 kilos.","成年熊猫约重 100 公斤。"),
            ("birth","bɜːrθ","n.","出生","At birth, a baby panda is very small.","出生时熊猫宝宝非常小。"),
            ("ocean","ˈoʊʃn","n.","海洋","The Pacific is the largest ocean.","太平洋是最大的海洋。"),
        ],
        "patterns": [
            ("数字 + 单位 + 形容词", "描述度量", "The mountain is <span class=\"slot\">8,848 meters high</span>."),
            ("the + 最高级 + in + 范围", "在一定范围内最…", "It's <span class=\"slot\">the longest river in China</span>."),
            ("比较级 + than any other…", "比任何其他都…", "It's <span class=\"slot\">higher than any other</span> mountain."),
        ],
        "grammar_title": "比较级与最高级深入运用 · 数字度量",
        "grammar_sections": [
            ("度量描述", [
                ("度量维度","问句","回答"),
                ("高度","How high is…?","It's … meters high."),
                ("长度","How long is…?","It's … kilometers long."),
                ("深度","How deep is…?","It's … meters deep."),
                ("宽度","How wide is…?","It's … meters wide."),
                ("重量","How heavy is…?","It's … kilos."),
            ]),
            ("最高级 + 范围", [
                ("结构","示例"),
                ("the + 最高级 + in + 地点","the tallest building in the world"),
                ("the + 最高级 + of + 群体","the tallest of the three boys"),
                ("one of the + 最高级 + 复数","one of the longest rivers"),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="The river is 6,000 meters length.">The river is 6,000 meters length.</span>（用 long 而不是 length）',
            '✅ <span class="correct" data-speak="The river is 6,000 meters long.">The river is 6,000 meters long.</span>',
            '❌ <span class="wrong" data-speak="It\'s the highest mountain of the world.">It\'s the highest mountain of the world.</span>（of 改为 in）',
            '✅ <span class="correct" data-speak="It\'s the highest mountain in the world.">It\'s the highest mountain in the world.</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[最高级] The Nile is the ____ (long) river in the world.","longest"),
            ("基础","★☆☆","[度量] How ____ is the mountain? — About 5,000 meters high.","high"),
            ("基础","★☆☆","[范围] China has the largest population ____ the world.","in"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改错] The Amazon is wider than any river in the world.","The Amazon is wider than any other river in the world."),
            ("提升","★★☆","[比较] The Caspian Sea is the deepest ____ all the lakes.","of"),
            ("提升","★★☆","[数字] 8,848.86 的英文读法？","eight thousand eight hundred forty-eight point eight six"),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 长城有多长？它长约 21,196 公里。","How long is the Great Wall? It's about 21,196 kilometers long."),
            ("挑战","★★★","[补全] A: What's the biggest animal on land?<br>B: ____","The elephant. / Actually, the African elephant is the biggest land animal."),
        ],
        "reading_title": "Amazing Animals: Pandas",
        "reading_text": [
            "Pandas are one of the most famous animals in the world. They live in the forests of China.",
            "At birth, a baby panda is about 15 cm long and weighs only 0.1 kg. It's so small that you can hold it in one hand! An adult panda weighs about 100 kg and is 1.5 meters long.",
            "Pandas eat bamboo. An adult panda eats about 12 to 38 kilos of bamboo every day. That's a lot!",
            "The panda is one of the most endangered animals in the world. There are only about 1,800 pandas living in the wild. We should do more to protect them.",
        ],
        "reading_gloss": [("bamboo","n. 竹子"),("endangered","adj. 濒危的"),("wild","n. 野生环境"),("protect","v. 保护")],
        "reading_qs": [
            ("阅读","★★☆","1. How much does a baby panda weigh at birth?","About 0.1 kg."),
            ("阅读","★★☆","2. How much bamboo does an adult panda eat per day?","12 to 38 kilos."),
            ("阅读","★★★","3. How many pandas are there in the wild?","About 1,800."),
        ],
        "exam_q_type": "语法填空", "exam_q": "用括号内单词的适当形式填空。",
        "exam_passage": ["The Great Wall is one of the (1)____ (great) wonders in the world. It's about 21,196 kilometers (2)____ (long). It's (3)____ (long) than any other wall in the world. The Great Wall is so (4)____ (famous) that millions of tourists visit it every year. It's the (5)____ (popular) tourist attraction in China."],
        "exam_options": [],
        "exam_answers": ["(1) greatest","(2) long","(3) longer","(4) famous","(5) most popular"],
        "writing_prompt": '请以"Amazing Places in China"为题，用最高级介绍中国的 3 个\"世界之最\"（自然或人文）。',
        "writing_framework": ["开头：中国有很多世界之最。","主体：介绍 3 个不同方面的高/长/大。","结尾：表达自豪感。"],
        "writing_model_en": "China is a country with many amazing places. First, Mount Qomolangma is the highest mountain in the world. It's 8,848.86 meters high. Second, the Yangtze River is the longest river in China. It's about 6,300 kilometers long. Third, the Great Wall is one of the greatest wonders. I'm proud that China has so many world records!",
        "writing_model_cn": "中国是一个有很多了不起地方的国家。第一，珠穆朗玛峰是世界最高峰，高 8848.86 米。第二，长江是中国最长的河流，长约 6300 公里。第三，长城是最伟大的奇迹之一。我为中国有这么多世界之最而自豪！",
        "project_title": "World Records Poster",
        "project_desc": "小组选择 5 个世界之最（自然或人造），用英语制作一张海报，包含数字和最高级描述。",
        "project_steps": ["每人选择一个世界之最。","查找数据和图片。","用英语写描述（含数字和最高级）。","制作海报并展示。"],
        "project_rubric": ["数据准确","正确使用最高级和度量表达","设计美观","口语表达流利"],
        "checklist": ["我能用最高级描述最好的事物","我能用数字+单位描述度量","我能比较不同事物","我能写世界之最的短文"],
        "feynman": "假装你在参加\"世界之最\"问答比赛，用英语回答主持人的提问。练习最高级和数字表达。",
        "review": ["默写 5 个表示度量的形容词（high/long/deep/wide/heavy）","用最高级写 5 个世界之最句子","用数字表达写 5 个度量句","写一段关于濒危动物的介绍"],
        "next_unit_title": "Making a Difference",
        "next_unit_desc": "最后一单元你将学习如何描述公益活动和社会责任，用英语讨论如何让世界变得更美好。",
    },

    "b2u08": {
        "num": "U8", "title": "Making a Difference", "topic": "社会责任",
        "en_topic": "Social Responsibility & Volunteer Work",
        "functions": "Talk about volunteer work and social issues",
        "grammar": "动词不定式作目的状语（to do / in order to）· make / let / help 使役动词",
        "writing": "How I Can Make a Difference",
        "can_do": ["能用 to do / in order to 表达目的","能用 make / help / let 结构","能谈论志愿服务和社会责任","能写一篇关于社会贡献的短文"],
        "dialogue_scene": "学校举办\"青年公益论坛\"，几位同学分享自己做志愿者的经历。",
        "dialogue": [
            ("Host","Welcome to our Youth Volunteer Forum. Let's hear from our speakers.","欢迎来到青年志愿论坛。来听听大家的分享。"),
            ("Chen Wei","I volunteer at an animal shelter to help stray dogs. I walk them every Saturday.","我在动物收容所做志愿者，帮助流浪狗。每周六带它们散步。"),
            ("Liu Na","I teach children in a village school to make a difference. I go there every summer.","我在一所乡村学校教书来改变现状。我每年暑假都去。"),
            ("Chen Wei","That's amazing! How does that make you feel?","太棒了！那让你感觉如何？"),
            ("Liu Na","It makes me feel useful. I help them learn English, and they teach me to be patient.","让我觉得自己很有用。我教他们英语，他们教我耐心。"),
            ("Host","Small actions can make a big difference. Let's all try to help others!","小行动能带来大改变。让我们一起帮助他人！"),
        ],
        "key_points": [
            "<strong>1.</strong> <em>I volunteer at an animal shelter to help stray dogs.</em> → <strong>to do</strong> 不定式表目的：\"为了……\"。",
            "<strong>2.</strong> <em>I teach children in a village school to make a difference.</em> → <strong>make a difference</strong> \"有所作为；带来改变\"。",
            "<strong>3.</strong> <em>It makes me feel useful.</em> → <strong>make + 人 + 动词原形</strong> \"让某人做/感到……\"。",
            "<strong>4.</strong> <em>They teach me to be patient.</em> → <strong>teach + 人 + to do</strong> \"教某人做……\"。",
        ],
        "vocab": [
            ("volunteer","ˌvɑːlənˈtɪr","v./n.","自愿；志愿者","I want to volunteer at the hospital.","我想在医院做志愿者。"),
            ("shelter","ˈʃeltər","n.","收容所；避难所","We donate food to the animal shelter.","我们向动物收容所捐食物。"),
            ("stray","streɪ","adj.","流浪的","There are many stray cats in the city.","城市里有很多流浪猫。"),
            ("difference","ˈdɪfrəns","n.","差异；不同","Small actions can make a big difference.","小行动能带来大不同。"),
            ("patient","ˈpeɪʃnt","adj.","耐心的","A good teacher should be patient.","好老师应该有耐心。"),
            ("action","ˈækʃn","n.","行动","Take action now! Don't wait.","现在就行动！不要等待。"),
            ("society","səˈsaɪəti","n.","社会","Everyone should contribute to society.","每个人都应为社会做贡献。"),
            ("community","kəˈmjuːnəti","n.","社区","We should help people in our community.","我们应该帮助社区里的人。"),
            ("homeless","ˈhoʊmləs","adj.","无家可归的","We raised money for homeless people.","我们为无家可归的人筹款。"),
            ("raise","reɪz","v.","筹集；提高","Let's raise money for the poor children.","让我们为贫困儿童筹款。"),
        ],
        "patterns": [
            ("…to do…（不定式表目的）", "为了……", "I went there <span class=\"slot\">to help</span> the children."),
            ("make / let / help + 人 + 动词", "使役动词", "It <span class=\"slot\">makes me feel</span> happy. / <span class=\"slot\">Let me help</span> you."),
            ("make a difference", "有所作为；带来改变", "Small things can <span class=\"slot\">make a big difference</span>."),
        ],
        "grammar_title": "不定式表目的 & 使役动词",
        "grammar_sections": [
            ("不定式作目的状语", [
                ("结构","含义","示例"),
                ("to + 动词原形","为了……","I called to invite you."),
                ("in order to + 动词","为了……（更正式）","He left early in order to catch the bus."),
            ]),
            ("使役动词 make / let / help", [
                ("动词","结构","示例"),
                ("make","make + 人 + 动词原形","It makes me cry."),
                ("let","let + 人 + 动词原形","Let me try."),
                ("help","help + 人 + (to) 动词","She helped me (to) clean."),
            ]),
        ],
        "grammar_tips": [
            '❌ <span class="wrong" data-speak="It makes me to feel happy.">It makes me to feel happy.</span>（make 后接动词原形，不加 to）',
            '✅ <span class="correct" data-speak="It makes me feel happy.">It makes me feel happy.</span>',
            '❌ <span class="wrong" data-speak="I went there for help him.">I went there for help him.</span>（表目的用 to do，不用 for do）',
            '✅ <span class="correct" data-speak="I went there to help him.">I went there to help him.</span>',
        ],
        "basic_qs": [
            ("基础","★☆☆","[目的] I volunteer ____ (help) old people.","to help"),
            ("基础","★☆☆","[make] Helping others ____ me ____ (feel) good.","makes; feel"),
            ("基础","★☆☆","[let] ____ me carry the box for you.","Let"),
        ],
        "mid_qs": [
            ("提升","★★☆","[改错] She helped me to carried the heavy bag.","She helped me carry the heavy bag."),
            ("提升","★★☆","[句型] I join the club. I want to make friends. (合并为带目的状语的句子)","I join the club to make friends."),
            ("提升","★★☆","[填空] He studied hard ____ ____ ____ (为了) pass the exam.","in order to"),
        ],
        "hard_qs": [
            ("挑战","★★★","[汉译英] 这个孩子的话让我思考了很多。","The child's words made me think a lot."),
            ("挑战","★★★","[补全] A: Why do you volunteer at the shelter?<br>B: I want ____ ____ a difference.","to make"),
        ],
        "reading_title": "Teens Who Make a Difference",
        "reading_text": [
            "Many young people around the world are making a difference. Here are two inspiring stories.",
            "Lin Tao, 14, noticed that many elderly people in his community lived alone. He started a \"Weekend Companion\" program. Every Saturday, he visits an elderly neighbor to chat and help with housework. \"It makes me feel useful to bring them joy,\" he says.",
            "Megan, 13, from the UK, loves reading. She collected hundreds of books and sent them to children in poor areas. \"I hope to open a window to the world for them,\" she said.",
            "These teens show us that age doesn't matter. You can make a difference starting today!",
        ],
        "reading_gloss": [("inspiring","adj. 鼓舞人心的"),("companion","n. 同伴；伙伴"),("elderly","adj. 年老的"),("joy","n. 欢乐；快乐"),("collect","v. 收集")],
        "reading_qs": [
            ("阅读","★★☆","1. What does Lin Tao do to help elderly people?","He visits them to chat and help with housework."),
            ("阅读","★★☆","2. What did Megan do to make a difference?","She collected books and sent them to children in poor areas."),
            ("阅读","★★★","3. What message do these stories give us?","Age doesn't matter. Everyone can make a difference."),
        ],
        "exam_q_type": "完形填空",
        "exam_q": "阅读短文，选择最佳选项。",
        "exam_passage": ["Last summer, I went to a village school (1)____ teach English. The children there made me (2)____ warm. They were so eager (3)____ learn. I taught them songs and games. They taught me (4)____ be strong. This experience made me (5)____ that small actions can make a big difference. I plan to go back next summer!"],
        "exam_options": [
            ("1.",{"A":"to","B":"for","C":"at","D":"in"}),
            ("2.",{"A":"feels","B":"feel","C":"felt","D":"feeling"}),
            ("3.",{"A":"to","B":"for","C":"at","D":"in"}),
            ("4.",{"A":"to","B":"for","C":"at","D":"how"}),
            ("5.",{"A":"realize","B":"realized","C":"realizing","D":"to realize"}),
        ],
        "exam_answers": ["1. A (to)","2. B (feel)","3. A (to)","4. A (to)","5. A (realize)"],
        "writing_prompt": '请以"How I Can Make a Difference"为题，写 70 词短文说说你打算通过什么行动为社会做贡献。',
        "writing_framework": ["开头：我想在哪个领域做出改变。","主体：具体行动（用 to do 表达目的）。","结尾：呼吁大家一起行动。"],
        "writing_model_en": "I want to make a difference by helping stray animals. I plan to volunteer at an animal shelter every weekend to take care of cats and dogs. I will also raise money to buy food for them. I hope my actions can make more people care about animal welfare. Making a difference doesn't need to be big—start with small things!",
        "writing_model_cn": "我想通过帮助流浪动物来做出改变。我打算每周末在动物收容所做志愿者，照顾猫狗。我还会筹钱为它们买食物。我希望我的行动能让更多人关注动物福利。做出改变不需要做大事——从小事开始！",
        "project_title": "Community Action Plan",
        "project_desc": "小组发现社区中存在一个问题（如环境差、老人孤独、流浪动物等），设计一份行动计划并用英语展示。",
        "project_steps": ["发现社区中的一个问题。","讨论解决方案（至少 3 条）。","用英语写出行动计划（用到 to do / make / help）。","在全班展示。"],
        "project_rubric": ["问题真实","方案可行","正确使用不定式表目的和使役动词","展示有号召力"],
        "checklist": ["我能用 to do 表达目的","我能用 make/let/help 使役结构","我能谈论志愿活动","我能写做贡献的短文"],
        "feynman": "假装你是公益组织创始人，用英语介绍你的公益项目，说明你为什么做这个项目以及它如何改变社会。",
        "review": ["用 to do 写 5 个目的状语","用 make/let/help 各写 2 句","写一段志愿者经历","复习不定式的各种用法"],
        "next_unit_title": "（八年级全部完成 🎉）",
        "next_unit_desc": "恭喜你完成了八年级全部 16 个单元的学习！接下来可以进入九年级的学习。",
    },
}
